// Code generated by ent, DO NOT EDIT.

package conversationmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the conversationmessage type in the database.
	Label = "conversation_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReportedInputTokens holds the string denoting the reported_input_tokens field in the database.
	FieldReportedInputTokens = "reported_input_tokens"
	// FieldReportedOutputTokens holds the string denoting the reported_output_tokens field in the database.
	FieldReportedOutputTokens = "reported_output_tokens"
	// FieldClientMessageID holds the string denoting the client_message_id field in the database.
	FieldClientMessageID = "client_message_id"
	// FieldGatewayRequestID holds the string denoting the gateway_request_id field in the database.
	FieldGatewayRequestID = "gateway_request_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeConversation holds the string denoting the conversation edge name in mutations.
	EdgeConversation = "conversation"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the conversationmessage in the database.
	Table = "conversation_messages"
	// ConversationTable is the table that holds the conversation relation/edge.
	ConversationTable = "conversation_messages"
	// ConversationInverseTable is the table name for the Conversation entity.
	// It exists in this package in order to avoid circular dependency with the "conversation" package.
	ConversationInverseTable = "conversations"
	// ConversationColumn is the table column denoting the conversation relation/edge.
	ConversationColumn = "conversation_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "conversation_messages"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for conversationmessage fields.
var Columns = []string{
	FieldID,
	FieldConversationID,
	FieldUserID,
	FieldRole,
	FieldContent,
	FieldModel,
	FieldStatus,
	FieldReportedInputTokens,
	FieldReportedOutputTokens,
	FieldClientMessageID,
	FieldGatewayRequestID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// ClientMessageIDValidator is a validator for the "client_message_id" field. It is called by the builders before save.
	ClientMessageIDValidator func(string) error
	// GatewayRequestIDValidator is a validator for the "gateway_request_id" field. It is called by the builders before save.
	GatewayRequestIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ConversationMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReportedInputTokens orders the results by the reported_input_tokens field.
func ByReportedInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedInputTokens, opts...).ToFunc()
}

// ByReportedOutputTokens orders the results by the reported_output_tokens field.
func ByReportedOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedOutputTokens, opts...).ToFunc()
}

// ByClientMessageID orders the results by the client_message_id field.
func ByClientMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientMessageID, opts...).ToFunc()
}

// ByGatewayRequestID orders the results by the gateway_request_id field.
func ByGatewayRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayRequestID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByConversationField orders the results by conversation field.
func ByConversationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConversationStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newConversationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConversationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConversationTable, ConversationColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
