// Code generated by ent, DO NOT EDIT.

package conversationmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldID, id))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldConversationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldUserID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldRole, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContent, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldModel, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldStatus, v))
}

// ReportedInputTokens applies equality check predicate on the "reported_input_tokens" field. It's identical to ReportedInputTokensEQ.
func ReportedInputTokens(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldReportedInputTokens, v))
}

// ReportedOutputTokens applies equality check predicate on the "reported_output_tokens" field. It's identical to ReportedOutputTokensEQ.
func ReportedOutputTokens(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldReportedOutputTokens, v))
}

// ClientMessageID applies equality check predicate on the "client_message_id" field. It's identical to ClientMessageIDEQ.
func ClientMessageID(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldClientMessageID, v))
}

// GatewayRequestID applies equality check predicate on the "gateway_request_id" field. It's identical to GatewayRequestIDEQ.
func GatewayRequestID(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldGatewayRequestID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldConversationID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldUserID, vs...))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldRole, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldContent, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldModel, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldStatus, v))
}

// ReportedInputTokensEQ applies the EQ predicate on the "reported_input_tokens" field.
func ReportedInputTokensEQ(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldReportedInputTokens, v))
}

// ReportedInputTokensNEQ applies the NEQ predicate on the "reported_input_tokens" field.
func ReportedInputTokensNEQ(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldReportedInputTokens, v))
}

// ReportedInputTokensIn applies the In predicate on the "reported_input_tokens" field.
func ReportedInputTokensIn(vs ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldReportedInputTokens, vs...))
}

// ReportedInputTokensNotIn applies the NotIn predicate on the "reported_input_tokens" field.
func ReportedInputTokensNotIn(vs ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldReportedInputTokens, vs...))
}

// ReportedInputTokensGT applies the GT predicate on the "reported_input_tokens" field.
func ReportedInputTokensGT(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldReportedInputTokens, v))
}

// ReportedInputTokensGTE applies the GTE predicate on the "reported_input_tokens" field.
func ReportedInputTokensGTE(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldReportedInputTokens, v))
}

// ReportedInputTokensLT applies the LT predicate on the "reported_input_tokens" field.
func ReportedInputTokensLT(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldReportedInputTokens, v))
}

// ReportedInputTokensLTE applies the LTE predicate on the "reported_input_tokens" field.
func ReportedInputTokensLTE(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldReportedInputTokens, v))
}

// ReportedInputTokensIsNil applies the IsNil predicate on the "reported_input_tokens" field.
func ReportedInputTokensIsNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIsNull(FieldReportedInputTokens))
}

// ReportedInputTokensNotNil applies the NotNil predicate on the "reported_input_tokens" field.
func ReportedInputTokensNotNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotNull(FieldReportedInputTokens))
}

// ReportedOutputTokensEQ applies the EQ predicate on the "reported_output_tokens" field.
func ReportedOutputTokensEQ(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldReportedOutputTokens, v))
}

// ReportedOutputTokensNEQ applies the NEQ predicate on the "reported_output_tokens" field.
func ReportedOutputTokensNEQ(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldReportedOutputTokens, v))
}

// ReportedOutputTokensIn applies the In predicate on the "reported_output_tokens" field.
func ReportedOutputTokensIn(vs ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldReportedOutputTokens, vs...))
}

// ReportedOutputTokensNotIn applies the NotIn predicate on the "reported_output_tokens" field.
func ReportedOutputTokensNotIn(vs ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldReportedOutputTokens, vs...))
}

// ReportedOutputTokensGT applies the GT predicate on the "reported_output_tokens" field.
func ReportedOutputTokensGT(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldReportedOutputTokens, v))
}

// ReportedOutputTokensGTE applies the GTE predicate on the "reported_output_tokens" field.
func ReportedOutputTokensGTE(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldReportedOutputTokens, v))
}

// ReportedOutputTokensLT applies the LT predicate on the "reported_output_tokens" field.
func ReportedOutputTokensLT(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldReportedOutputTokens, v))
}

// ReportedOutputTokensLTE applies the LTE predicate on the "reported_output_tokens" field.
func ReportedOutputTokensLTE(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldReportedOutputTokens, v))
}

// ReportedOutputTokensIsNil applies the IsNil predicate on the "reported_output_tokens" field.
func ReportedOutputTokensIsNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIsNull(FieldReportedOutputTokens))
}

// ReportedOutputTokensNotNil applies the NotNil predicate on the "reported_output_tokens" field.
func ReportedOutputTokensNotNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotNull(FieldReportedOutputTokens))
}

// ClientMessageIDEQ applies the EQ predicate on the "client_message_id" field.
func ClientMessageIDEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldClientMessageID, v))
}

// ClientMessageIDNEQ applies the NEQ predicate on the "client_message_id" field.
func ClientMessageIDNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldClientMessageID, v))
}

// ClientMessageIDIn applies the In predicate on the "client_message_id" field.
func ClientMessageIDIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldClientMessageID, vs...))
}

// ClientMessageIDNotIn applies the NotIn predicate on the "client_message_id" field.
func ClientMessageIDNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldClientMessageID, vs...))
}

// ClientMessageIDGT applies the GT predicate on the "client_message_id" field.
func ClientMessageIDGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldClientMessageID, v))
}

// ClientMessageIDGTE applies the GTE predicate on the "client_message_id" field.
func ClientMessageIDGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldClientMessageID, v))
}

// ClientMessageIDLT applies the LT predicate on the "client_message_id" field.
func ClientMessageIDLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldClientMessageID, v))
}

// ClientMessageIDLTE applies the LTE predicate on the "client_message_id" field.
func ClientMessageIDLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldClientMessageID, v))
}

// ClientMessageIDContains applies the Contains predicate on the "client_message_id" field.
func ClientMessageIDContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldClientMessageID, v))
}

// ClientMessageIDHasPrefix applies the HasPrefix predicate on the "client_message_id" field.
func ClientMessageIDHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldClientMessageID, v))
}

// ClientMessageIDHasSuffix applies the HasSuffix predicate on the "client_message_id" field.
func ClientMessageIDHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldClientMessageID, v))
}

// ClientMessageIDEqualFold applies the EqualFold predicate on the "client_message_id" field.
func ClientMessageIDEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldClientMessageID, v))
}

// ClientMessageIDContainsFold applies the ContainsFold predicate on the "client_message_id" field.
func ClientMessageIDContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldClientMessageID, v))
}

// GatewayRequestIDEQ applies the EQ predicate on the "gateway_request_id" field.
func GatewayRequestIDEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldGatewayRequestID, v))
}

// GatewayRequestIDNEQ applies the NEQ predicate on the "gateway_request_id" field.
func GatewayRequestIDNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldGatewayRequestID, v))
}

// GatewayRequestIDIn applies the In predicate on the "gateway_request_id" field.
func GatewayRequestIDIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldGatewayRequestID, vs...))
}

// GatewayRequestIDNotIn applies the NotIn predicate on the "gateway_request_id" field.
func GatewayRequestIDNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldGatewayRequestID, vs...))
}

// GatewayRequestIDGT applies the GT predicate on the "gateway_request_id" field.
func GatewayRequestIDGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldGatewayRequestID, v))
}

// GatewayRequestIDGTE applies the GTE predicate on the "gateway_request_id" field.
func GatewayRequestIDGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldGatewayRequestID, v))
}

// GatewayRequestIDLT applies the LT predicate on the "gateway_request_id" field.
func GatewayRequestIDLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldGatewayRequestID, v))
}

// GatewayRequestIDLTE applies the LTE predicate on the "gateway_request_id" field.
func GatewayRequestIDLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldGatewayRequestID, v))
}

// GatewayRequestIDContains applies the Contains predicate on the "gateway_request_id" field.
func GatewayRequestIDContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldGatewayRequestID, v))
}

// GatewayRequestIDHasPrefix applies the HasPrefix predicate on the "gateway_request_id" field.
func GatewayRequestIDHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldGatewayRequestID, v))
}

// GatewayRequestIDHasSuffix applies the HasSuffix predicate on the "gateway_request_id" field.
func GatewayRequestIDHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldGatewayRequestID, v))
}

// GatewayRequestIDIsNil applies the IsNil predicate on the "gateway_request_id" field.
func GatewayRequestIDIsNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIsNull(FieldGatewayRequestID))
}

// GatewayRequestIDNotNil applies the NotNil predicate on the "gateway_request_id" field.
func GatewayRequestIDNotNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotNull(FieldGatewayRequestID))
}

// GatewayRequestIDEqualFold applies the EqualFold predicate on the "gateway_request_id" field.
func GatewayRequestIDEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldGatewayRequestID, v))
}

// GatewayRequestIDContainsFold applies the ContainsFold predicate on the "gateway_request_id" field.
func GatewayRequestIDContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldGatewayRequestID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasConversation applies the HasEdge predicate on the "conversation" edge.
func HasConversation() predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConversationTable, ConversationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConversationWith applies the HasEdge predicate on the "conversation" edge with a given conditions (other predicates).
func HasConversationWith(preds ...predicate.Conversation) predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := newConversationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.NotPredicates(p))
}
