// Code generated by ent, DO NOT EDIT.

package paygorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paygorder type in the database.
	Label = "payg_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldClientSn holds the string denoting the client_sn field in the database.
	FieldClientSn = "client_sn"
	// FieldSn holds the string denoting the sn field in the database.
	FieldSn = "sn"
	// FieldAmountYuan holds the string denoting the amount_yuan field in the database.
	FieldAmountYuan = "amount_yuan"
	// FieldAmountCent holds the string denoting the amount_cent field in the database.
	FieldAmountCent = "amount_cent"
	// FieldCreditAmount holds the string denoting the credit_amount field in the database.
	FieldCreditAmount = "credit_amount"
	// FieldPayway holds the string denoting the payway field in the database.
	FieldPayway = "payway"
	// FieldPaywayName holds the string denoting the payway_name field in the database.
	FieldPaywayName = "payway_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the paygorder in the database.
	Table = "payg_orders"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "payg_orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for paygorder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldClientSn,
	FieldSn,
	FieldAmountYuan,
	FieldAmountCent,
	FieldCreditAmount,
	FieldPayway,
	FieldPaywayName,
	FieldStatus,
	FieldPaidAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ClientSnValidator is a validator for the "client_sn" field. It is called by the builders before save.
	ClientSnValidator func(string) error
	// SnValidator is a validator for the "sn" field. It is called by the builders before save.
	SnValidator func(string) error
	// DefaultPayway holds the default value on creation for the "payway" field.
	DefaultPayway string
	// PaywayValidator is a validator for the "payway" field. It is called by the builders before save.
	PaywayValidator func(string) error
	// DefaultPaywayName holds the default value on creation for the "payway_name" field.
	DefaultPaywayName string
	// PaywayNameValidator is a validator for the "payway_name" field. It is called by the builders before save.
	PaywayNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the PaygOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByClientSn orders the results by the client_sn field.
func ByClientSn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientSn, opts...).ToFunc()
}

// BySn orders the results by the sn field.
func BySn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSn, opts...).ToFunc()
}

// ByAmountYuan orders the results by the amount_yuan field.
func ByAmountYuan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountYuan, opts...).ToFunc()
}

// ByAmountCent orders the results by the amount_cent field.
func ByAmountCent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCent, opts...).ToFunc()
}

// ByCreditAmount orders the results by the credit_amount field.
func ByCreditAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditAmount, opts...).ToFunc()
}

// ByPayway orders the results by the payway field.
func ByPayway(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayway, opts...).ToFunc()
}

// ByPaywayName orders the results by the payway_name field.
func ByPaywayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaywayName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
