// Code generated by ent, DO NOT EDIT.

package paygorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldUserID, v))
}

// ClientSn applies equality check predicate on the "client_sn" field. It's identical to ClientSnEQ.
func ClientSn(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldClientSn, v))
}

// Sn applies equality check predicate on the "sn" field. It's identical to SnEQ.
func Sn(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldSn, v))
}

// AmountYuan applies equality check predicate on the "amount_yuan" field. It's identical to AmountYuanEQ.
func AmountYuan(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldAmountYuan, v))
}

// AmountCent applies equality check predicate on the "amount_cent" field. It's identical to AmountCentEQ.
func AmountCent(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldAmountCent, v))
}

// CreditAmount applies equality check predicate on the "credit_amount" field. It's identical to CreditAmountEQ.
func CreditAmount(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldCreditAmount, v))
}

// Payway applies equality check predicate on the "payway" field. It's identical to PaywayEQ.
func Payway(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldPayway, v))
}

// PaywayName applies equality check predicate on the "payway_name" field. It's identical to PaywayNameEQ.
func PaywayName(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldPaywayName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldStatus, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldPaidAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// ClientSnEQ applies the EQ predicate on the "client_sn" field.
func ClientSnEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldClientSn, v))
}

// ClientSnNEQ applies the NEQ predicate on the "client_sn" field.
func ClientSnNEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldClientSn, v))
}

// ClientSnIn applies the In predicate on the "client_sn" field.
func ClientSnIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldClientSn, vs...))
}

// ClientSnNotIn applies the NotIn predicate on the "client_sn" field.
func ClientSnNotIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldClientSn, vs...))
}

// ClientSnGT applies the GT predicate on the "client_sn" field.
func ClientSnGT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldClientSn, v))
}

// ClientSnGTE applies the GTE predicate on the "client_sn" field.
func ClientSnGTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldClientSn, v))
}

// ClientSnLT applies the LT predicate on the "client_sn" field.
func ClientSnLT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldClientSn, v))
}

// ClientSnLTE applies the LTE predicate on the "client_sn" field.
func ClientSnLTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldClientSn, v))
}

// ClientSnContains applies the Contains predicate on the "client_sn" field.
func ClientSnContains(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContains(FieldClientSn, v))
}

// ClientSnHasPrefix applies the HasPrefix predicate on the "client_sn" field.
func ClientSnHasPrefix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasPrefix(FieldClientSn, v))
}

// ClientSnHasSuffix applies the HasSuffix predicate on the "client_sn" field.
func ClientSnHasSuffix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasSuffix(FieldClientSn, v))
}

// ClientSnEqualFold applies the EqualFold predicate on the "client_sn" field.
func ClientSnEqualFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEqualFold(FieldClientSn, v))
}

// ClientSnContainsFold applies the ContainsFold predicate on the "client_sn" field.
func ClientSnContainsFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContainsFold(FieldClientSn, v))
}

// SnEQ applies the EQ predicate on the "sn" field.
func SnEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldSn, v))
}

// SnNEQ applies the NEQ predicate on the "sn" field.
func SnNEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldSn, v))
}

// SnIn applies the In predicate on the "sn" field.
func SnIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldSn, vs...))
}

// SnNotIn applies the NotIn predicate on the "sn" field.
func SnNotIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldSn, vs...))
}

// SnGT applies the GT predicate on the "sn" field.
func SnGT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldSn, v))
}

// SnGTE applies the GTE predicate on the "sn" field.
func SnGTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldSn, v))
}

// SnLT applies the LT predicate on the "sn" field.
func SnLT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldSn, v))
}

// SnLTE applies the LTE predicate on the "sn" field.
func SnLTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldSn, v))
}

// SnContains applies the Contains predicate on the "sn" field.
func SnContains(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContains(FieldSn, v))
}

// SnHasPrefix applies the HasPrefix predicate on the "sn" field.
func SnHasPrefix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasPrefix(FieldSn, v))
}

// SnHasSuffix applies the HasSuffix predicate on the "sn" field.
func SnHasSuffix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasSuffix(FieldSn, v))
}

// SnIsNil applies the IsNil predicate on the "sn" field.
func SnIsNil() predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIsNull(FieldSn))
}

// SnNotNil applies the NotNil predicate on the "sn" field.
func SnNotNil() predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotNull(FieldSn))
}

// SnEqualFold applies the EqualFold predicate on the "sn" field.
func SnEqualFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEqualFold(FieldSn, v))
}

// SnContainsFold applies the ContainsFold predicate on the "sn" field.
func SnContainsFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContainsFold(FieldSn, v))
}

// AmountYuanEQ applies the EQ predicate on the "amount_yuan" field.
func AmountYuanEQ(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldAmountYuan, v))
}

// AmountYuanNEQ applies the NEQ predicate on the "amount_yuan" field.
func AmountYuanNEQ(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldAmountYuan, v))
}

// AmountYuanIn applies the In predicate on the "amount_yuan" field.
func AmountYuanIn(vs ...float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldAmountYuan, vs...))
}

// AmountYuanNotIn applies the NotIn predicate on the "amount_yuan" field.
func AmountYuanNotIn(vs ...float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldAmountYuan, vs...))
}

// AmountYuanGT applies the GT predicate on the "amount_yuan" field.
func AmountYuanGT(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldAmountYuan, v))
}

// AmountYuanGTE applies the GTE predicate on the "amount_yuan" field.
func AmountYuanGTE(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldAmountYuan, v))
}

// AmountYuanLT applies the LT predicate on the "amount_yuan" field.
func AmountYuanLT(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldAmountYuan, v))
}

// AmountYuanLTE applies the LTE predicate on the "amount_yuan" field.
func AmountYuanLTE(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldAmountYuan, v))
}

// AmountCentEQ applies the EQ predicate on the "amount_cent" field.
func AmountCentEQ(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldAmountCent, v))
}

// AmountCentNEQ applies the NEQ predicate on the "amount_cent" field.
func AmountCentNEQ(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldAmountCent, v))
}

// AmountCentIn applies the In predicate on the "amount_cent" field.
func AmountCentIn(vs ...int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldAmountCent, vs...))
}

// AmountCentNotIn applies the NotIn predicate on the "amount_cent" field.
func AmountCentNotIn(vs ...int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldAmountCent, vs...))
}

// AmountCentGT applies the GT predicate on the "amount_cent" field.
func AmountCentGT(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldAmountCent, v))
}

// AmountCentGTE applies the GTE predicate on the "amount_cent" field.
func AmountCentGTE(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldAmountCent, v))
}

// AmountCentLT applies the LT predicate on the "amount_cent" field.
func AmountCentLT(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldAmountCent, v))
}

// AmountCentLTE applies the LTE predicate on the "amount_cent" field.
func AmountCentLTE(v int64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldAmountCent, v))
}

// CreditAmountEQ applies the EQ predicate on the "credit_amount" field.
func CreditAmountEQ(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldCreditAmount, v))
}

// CreditAmountNEQ applies the NEQ predicate on the "credit_amount" field.
func CreditAmountNEQ(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldCreditAmount, v))
}

// CreditAmountIn applies the In predicate on the "credit_amount" field.
func CreditAmountIn(vs ...float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldCreditAmount, vs...))
}

// CreditAmountNotIn applies the NotIn predicate on the "credit_amount" field.
func CreditAmountNotIn(vs ...float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldCreditAmount, vs...))
}

// CreditAmountGT applies the GT predicate on the "credit_amount" field.
func CreditAmountGT(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldCreditAmount, v))
}

// CreditAmountGTE applies the GTE predicate on the "credit_amount" field.
func CreditAmountGTE(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldCreditAmount, v))
}

// CreditAmountLT applies the LT predicate on the "credit_amount" field.
func CreditAmountLT(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldCreditAmount, v))
}

// CreditAmountLTE applies the LTE predicate on the "credit_amount" field.
func CreditAmountLTE(v float64) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldCreditAmount, v))
}

// PaywayEQ applies the EQ predicate on the "payway" field.
func PaywayEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldPayway, v))
}

// PaywayNEQ applies the NEQ predicate on the "payway" field.
func PaywayNEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldPayway, v))
}

// PaywayIn applies the In predicate on the "payway" field.
func PaywayIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldPayway, vs...))
}

// PaywayNotIn applies the NotIn predicate on the "payway" field.
func PaywayNotIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldPayway, vs...))
}

// PaywayGT applies the GT predicate on the "payway" field.
func PaywayGT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldPayway, v))
}

// PaywayGTE applies the GTE predicate on the "payway" field.
func PaywayGTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldPayway, v))
}

// PaywayLT applies the LT predicate on the "payway" field.
func PaywayLT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldPayway, v))
}

// PaywayLTE applies the LTE predicate on the "payway" field.
func PaywayLTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldPayway, v))
}

// PaywayContains applies the Contains predicate on the "payway" field.
func PaywayContains(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContains(FieldPayway, v))
}

// PaywayHasPrefix applies the HasPrefix predicate on the "payway" field.
func PaywayHasPrefix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasPrefix(FieldPayway, v))
}

// PaywayHasSuffix applies the HasSuffix predicate on the "payway" field.
func PaywayHasSuffix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasSuffix(FieldPayway, v))
}

// PaywayEqualFold applies the EqualFold predicate on the "payway" field.
func PaywayEqualFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEqualFold(FieldPayway, v))
}

// PaywayContainsFold applies the ContainsFold predicate on the "payway" field.
func PaywayContainsFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContainsFold(FieldPayway, v))
}

// PaywayNameEQ applies the EQ predicate on the "payway_name" field.
func PaywayNameEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldPaywayName, v))
}

// PaywayNameNEQ applies the NEQ predicate on the "payway_name" field.
func PaywayNameNEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldPaywayName, v))
}

// PaywayNameIn applies the In predicate on the "payway_name" field.
func PaywayNameIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldPaywayName, vs...))
}

// PaywayNameNotIn applies the NotIn predicate on the "payway_name" field.
func PaywayNameNotIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldPaywayName, vs...))
}

// PaywayNameGT applies the GT predicate on the "payway_name" field.
func PaywayNameGT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldPaywayName, v))
}

// PaywayNameGTE applies the GTE predicate on the "payway_name" field.
func PaywayNameGTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldPaywayName, v))
}

// PaywayNameLT applies the LT predicate on the "payway_name" field.
func PaywayNameLT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldPaywayName, v))
}

// PaywayNameLTE applies the LTE predicate on the "payway_name" field.
func PaywayNameLTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldPaywayName, v))
}

// PaywayNameContains applies the Contains predicate on the "payway_name" field.
func PaywayNameContains(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContains(FieldPaywayName, v))
}

// PaywayNameHasPrefix applies the HasPrefix predicate on the "payway_name" field.
func PaywayNameHasPrefix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasPrefix(FieldPaywayName, v))
}

// PaywayNameHasSuffix applies the HasSuffix predicate on the "payway_name" field.
func PaywayNameHasSuffix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasSuffix(FieldPaywayName, v))
}

// PaywayNameEqualFold applies the EqualFold predicate on the "payway_name" field.
func PaywayNameEqualFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEqualFold(FieldPaywayName, v))
}

// PaywayNameContainsFold applies the ContainsFold predicate on the "payway_name" field.
func PaywayNameContainsFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContainsFold(FieldPaywayName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldContainsFold(FieldStatus, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.PaygOrder {
	return predicate.PaygOrder(sql.FieldNotNull(FieldPaidAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PaygOrder {
	return predicate.PaygOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PaygOrder {
	return predicate.PaygOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaygOrder) predicate.PaygOrder {
	return predicate.PaygOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaygOrder) predicate.PaygOrder {
	return predicate.PaygOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaygOrder) predicate.PaygOrder {
	return predicate.PaygOrder(sql.NotPredicates(p))
}
