// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationMessage is the model entity for the ConversationMessage schema.
type ConversationMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID int64 `json:"conversation_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Message role: user, assistant
	Role string `json:"role,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Message status: complete, error
	Status string `json:"status,omitempty"`
	// Client-reported prompt token count (display-only, not for billing)
	ReportedInputTokens *int `json:"reported_input_tokens,omitempty"`
	// Client-reported completion token count (display-only, not for billing)
	ReportedOutputTokens *int `json:"reported_output_tokens,omitempty"`
	// Client-generated identifier used for idempotent append
	ClientMessageID string `json:"client_message_id,omitempty"`
	// Upstream gateway request identifier, when available
	GatewayRequestID *string `json:"gateway_request_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConversationMessageQuery when eager-loading is set.
	Edges        ConversationMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConversationMessageEdges holds the relations/edges for other nodes in the graph.
type ConversationMessageEdges struct {
	// Conversation holds the value of the conversation edge.
	Conversation *Conversation `json:"conversation,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ConversationOrErr returns the Conversation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationMessageEdges) ConversationOrErr() (*Conversation, error) {
	if e.Conversation != nil {
		return e.Conversation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: conversation.Label}
	}
	return nil, &NotLoadedError{edge: "conversation"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationMessageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConversationMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversationmessage.FieldID, conversationmessage.FieldConversationID, conversationmessage.FieldUserID, conversationmessage.FieldReportedInputTokens, conversationmessage.FieldReportedOutputTokens:
			values[i] = new(sql.NullInt64)
		case conversationmessage.FieldRole, conversationmessage.FieldContent, conversationmessage.FieldModel, conversationmessage.FieldStatus, conversationmessage.FieldClientMessageID, conversationmessage.FieldGatewayRequestID:
			values[i] = new(sql.NullString)
		case conversationmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConversationMessage fields.
func (_m *ConversationMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversationmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case conversationmessage.FieldConversationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = value.Int64
			}
		case conversationmessage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case conversationmessage.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case conversationmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case conversationmessage.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case conversationmessage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case conversationmessage.FieldReportedInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reported_input_tokens", values[i])
			} else if value.Valid {
				_m.ReportedInputTokens = new(int)
				*_m.ReportedInputTokens = int(value.Int64)
			}
		case conversationmessage.FieldReportedOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reported_output_tokens", values[i])
			} else if value.Valid {
				_m.ReportedOutputTokens = new(int)
				*_m.ReportedOutputTokens = int(value.Int64)
			}
		case conversationmessage.FieldClientMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_message_id", values[i])
			} else if value.Valid {
				_m.ClientMessageID = value.String
			}
		case conversationmessage.FieldGatewayRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_request_id", values[i])
			} else if value.Valid {
				_m.GatewayRequestID = new(string)
				*_m.GatewayRequestID = value.String
			}
		case conversationmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConversationMessage.
// This includes values selected through modifiers, order, etc.
func (_m *ConversationMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConversation queries the "conversation" edge of the ConversationMessage entity.
func (_m *ConversationMessage) QueryConversation() *ConversationQuery {
	return NewConversationMessageClient(_m.config).QueryConversation(_m)
}

// QueryUser queries the "user" edge of the ConversationMessage entity.
func (_m *ConversationMessage) QueryUser() *UserQuery {
	return NewConversationMessageClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ConversationMessage.
// Note that you need to call ConversationMessage.Unwrap() before calling this method if this ConversationMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConversationMessage) Update() *ConversationMessageUpdateOne {
	return NewConversationMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConversationMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConversationMessage) Unwrap() *ConversationMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConversationMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConversationMessage) String() string {
	var builder strings.Builder
	builder.WriteString("ConversationMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("conversation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversationID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ReportedInputTokens; v != nil {
		builder.WriteString("reported_input_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReportedOutputTokens; v != nil {
		builder.WriteString("reported_output_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("client_message_id=")
	builder.WriteString(_m.ClientMessageID)
	builder.WriteString(", ")
	if v := _m.GatewayRequestID; v != nil {
		builder.WriteString("gateway_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConversationMessages is a parsable slice of ConversationMessage.
type ConversationMessages []*ConversationMessage
