// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationMessageCreate is the builder for creating a ConversationMessage entity.
type ConversationMessageCreate struct {
	config
	mutation *ConversationMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConversationID sets the "conversation_id" field.
func (_c *ConversationMessageCreate) SetConversationID(v int64) *ConversationMessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ConversationMessageCreate) SetUserID(v int64) *ConversationMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ConversationMessageCreate) SetRole(v string) *ConversationMessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ConversationMessageCreate) SetContent(v string) *ConversationMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableContent(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ConversationMessageCreate) SetModel(v string) *ConversationMessageCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableModel(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ConversationMessageCreate) SetStatus(v string) *ConversationMessageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableStatus(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReportedInputTokens sets the "reported_input_tokens" field.
func (_c *ConversationMessageCreate) SetReportedInputTokens(v int) *ConversationMessageCreate {
	_c.mutation.SetReportedInputTokens(v)
	return _c
}

// SetNillableReportedInputTokens sets the "reported_input_tokens" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableReportedInputTokens(v *int) *ConversationMessageCreate {
	if v != nil {
		_c.SetReportedInputTokens(*v)
	}
	return _c
}

// SetReportedOutputTokens sets the "reported_output_tokens" field.
func (_c *ConversationMessageCreate) SetReportedOutputTokens(v int) *ConversationMessageCreate {
	_c.mutation.SetReportedOutputTokens(v)
	return _c
}

// SetNillableReportedOutputTokens sets the "reported_output_tokens" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableReportedOutputTokens(v *int) *ConversationMessageCreate {
	if v != nil {
		_c.SetReportedOutputTokens(*v)
	}
	return _c
}

// SetClientMessageID sets the "client_message_id" field.
func (_c *ConversationMessageCreate) SetClientMessageID(v string) *ConversationMessageCreate {
	_c.mutation.SetClientMessageID(v)
	return _c
}

// SetGatewayRequestID sets the "gateway_request_id" field.
func (_c *ConversationMessageCreate) SetGatewayRequestID(v string) *ConversationMessageCreate {
	_c.mutation.SetGatewayRequestID(v)
	return _c
}

// SetNillableGatewayRequestID sets the "gateway_request_id" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableGatewayRequestID(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetGatewayRequestID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationMessageCreate) SetCreatedAt(v time.Time) *ConversationMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableCreatedAt(v *time.Time) *ConversationMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_c *ConversationMessageCreate) SetConversation(v *Conversation) *ConversationMessageCreate {
	return _c.SetConversationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ConversationMessageCreate) SetUser(v *User) *ConversationMessageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_c *ConversationMessageCreate) Mutation() *ConversationMessageMutation {
	return _c.mutation
}

// Save creates the ConversationMessage in the database.
func (_c *ConversationMessageCreate) Save(ctx context.Context) (*ConversationMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationMessageCreate) SaveX(ctx context.Context) *ConversationMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationMessageCreate) defaults() {
	if _, ok := _c.mutation.Content(); !ok {
		v := conversationmessage.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := conversationmessage.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := conversationmessage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversationmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationMessageCreate) check() error {
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "ConversationMessage.conversation_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ConversationMessage.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ConversationMessage.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := conversationmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ConversationMessage.content"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ConversationMessage.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := conversationmessage.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ConversationMessage.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := conversationmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientMessageID(); !ok {
		return &ValidationError{Name: "client_message_id", err: errors.New(`ent: missing required field "ConversationMessage.client_message_id"`)}
	}
	if v, ok := _c.mutation.ClientMessageID(); ok {
		if err := conversationmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.client_message_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.GatewayRequestID(); ok {
		if err := conversationmessage.GatewayRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "gateway_request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.gateway_request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConversationMessage.created_at"`)}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "ConversationMessage.conversation"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ConversationMessage.user"`)}
	}
	return nil
}

func (_c *ConversationMessageCreate) sqlSave(ctx context.Context) (*ConversationMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationMessageCreate) createSpec() (*ConversationMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ConversationMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversationmessage.Table, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(conversationmessage.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(conversationmessage.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(conversationmessage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReportedInputTokens(); ok {
		_spec.SetField(conversationmessage.FieldReportedInputTokens, field.TypeInt, value)
		_node.ReportedInputTokens = &value
	}
	if value, ok := _c.mutation.ReportedOutputTokens(); ok {
		_spec.SetField(conversationmessage.FieldReportedOutputTokens, field.TypeInt, value)
		_node.ReportedOutputTokens = &value
	}
	if value, ok := _c.mutation.ClientMessageID(); ok {
		_spec.SetField(conversationmessage.FieldClientMessageID, field.TypeString, value)
		_node.ClientMessageID = value
	}
	if value, ok := _c.mutation.GatewayRequestID(); ok {
		_spec.SetField(conversationmessage.FieldGatewayRequestID, field.TypeString, value)
		_node.GatewayRequestID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversationmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.UserTable,
			Columns: []string{conversationmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationMessage.Create().
//		SetConversationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationMessageCreate) OnConflict(opts ...sql.ConflictOption) *ConversationMessageUpsertOne {
	_c.conflict = opts
	return &ConversationMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationMessageCreate) OnConflictColumns(columns ...string) *ConversationMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationMessageUpsertOne{
		create: _c,
	}
}

type (
	// ConversationMessageUpsertOne is the builder for "upsert"-ing
	//  one ConversationMessage node.
	ConversationMessageUpsertOne struct {
		create *ConversationMessageCreate
	}

	// ConversationMessageUpsert is the "OnConflict" setter.
	ConversationMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetConversationID sets the "conversation_id" field.
func (u *ConversationMessageUpsert) SetConversationID(v int64) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateConversationID() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldConversationID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ConversationMessageUpsert) SetUserID(v int64) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateUserID() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldUserID)
	return u
}

// SetRole sets the "role" field.
func (u *ConversationMessageUpsert) SetRole(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateRole() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldRole)
	return u
}

// SetContent sets the "content" field.
func (u *ConversationMessageUpsert) SetContent(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateContent() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldContent)
	return u
}

// SetModel sets the "model" field.
func (u *ConversationMessageUpsert) SetModel(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateModel() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldModel)
	return u
}

// SetStatus sets the "status" field.
func (u *ConversationMessageUpsert) SetStatus(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateStatus() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldStatus)
	return u
}

// SetReportedInputTokens sets the "reported_input_tokens" field.
func (u *ConversationMessageUpsert) SetReportedInputTokens(v int) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldReportedInputTokens, v)
	return u
}

// UpdateReportedInputTokens sets the "reported_input_tokens" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateReportedInputTokens() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldReportedInputTokens)
	return u
}

// AddReportedInputTokens adds v to the "reported_input_tokens" field.
func (u *ConversationMessageUpsert) AddReportedInputTokens(v int) *ConversationMessageUpsert {
	u.Add(conversationmessage.FieldReportedInputTokens, v)
	return u
}

// ClearReportedInputTokens clears the value of the "reported_input_tokens" field.
func (u *ConversationMessageUpsert) ClearReportedInputTokens() *ConversationMessageUpsert {
	u.SetNull(conversationmessage.FieldReportedInputTokens)
	return u
}

// SetReportedOutputTokens sets the "reported_output_tokens" field.
func (u *ConversationMessageUpsert) SetReportedOutputTokens(v int) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldReportedOutputTokens, v)
	return u
}

// UpdateReportedOutputTokens sets the "reported_output_tokens" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateReportedOutputTokens() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldReportedOutputTokens)
	return u
}

// AddReportedOutputTokens adds v to the "reported_output_tokens" field.
func (u *ConversationMessageUpsert) AddReportedOutputTokens(v int) *ConversationMessageUpsert {
	u.Add(conversationmessage.FieldReportedOutputTokens, v)
	return u
}

// ClearReportedOutputTokens clears the value of the "reported_output_tokens" field.
func (u *ConversationMessageUpsert) ClearReportedOutputTokens() *ConversationMessageUpsert {
	u.SetNull(conversationmessage.FieldReportedOutputTokens)
	return u
}

// SetClientMessageID sets the "client_message_id" field.
func (u *ConversationMessageUpsert) SetClientMessageID(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldClientMessageID, v)
	return u
}

// UpdateClientMessageID sets the "client_message_id" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateClientMessageID() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldClientMessageID)
	return u
}

// SetGatewayRequestID sets the "gateway_request_id" field.
func (u *ConversationMessageUpsert) SetGatewayRequestID(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldGatewayRequestID, v)
	return u
}

// UpdateGatewayRequestID sets the "gateway_request_id" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateGatewayRequestID() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldGatewayRequestID)
	return u
}

// ClearGatewayRequestID clears the value of the "gateway_request_id" field.
func (u *ConversationMessageUpsert) ClearGatewayRequestID() *ConversationMessageUpsert {
	u.SetNull(conversationmessage.FieldGatewayRequestID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationMessageUpsertOne) UpdateNewValues() *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(conversationmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConversationMessageUpsertOne) Ignore() *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationMessageUpsertOne) DoNothing() *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationMessageCreate.OnConflict
// documentation for more info.
func (u *ConversationMessageUpsertOne) Update(set func(*ConversationMessageUpsert)) *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ConversationMessageUpsertOne) SetConversationID(v int64) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateConversationID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ConversationMessageUpsertOne) SetUserID(v int64) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateUserID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *ConversationMessageUpsertOne) SetRole(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateRole() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *ConversationMessageUpsertOne) SetContent(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateContent() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateContent()
	})
}

// SetModel sets the "model" field.
func (u *ConversationMessageUpsertOne) SetModel(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateModel() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateModel()
	})
}

// SetStatus sets the "status" field.
func (u *ConversationMessageUpsertOne) SetStatus(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateStatus() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetReportedInputTokens sets the "reported_input_tokens" field.
func (u *ConversationMessageUpsertOne) SetReportedInputTokens(v int) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetReportedInputTokens(v)
	})
}

// AddReportedInputTokens adds v to the "reported_input_tokens" field.
func (u *ConversationMessageUpsertOne) AddReportedInputTokens(v int) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.AddReportedInputTokens(v)
	})
}

// UpdateReportedInputTokens sets the "reported_input_tokens" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateReportedInputTokens() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateReportedInputTokens()
	})
}

// ClearReportedInputTokens clears the value of the "reported_input_tokens" field.
func (u *ConversationMessageUpsertOne) ClearReportedInputTokens() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearReportedInputTokens()
	})
}

// SetReportedOutputTokens sets the "reported_output_tokens" field.
func (u *ConversationMessageUpsertOne) SetReportedOutputTokens(v int) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetReportedOutputTokens(v)
	})
}

// AddReportedOutputTokens adds v to the "reported_output_tokens" field.
func (u *ConversationMessageUpsertOne) AddReportedOutputTokens(v int) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.AddReportedOutputTokens(v)
	})
}

// UpdateReportedOutputTokens sets the "reported_output_tokens" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateReportedOutputTokens() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateReportedOutputTokens()
	})
}

// ClearReportedOutputTokens clears the value of the "reported_output_tokens" field.
func (u *ConversationMessageUpsertOne) ClearReportedOutputTokens() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearReportedOutputTokens()
	})
}

// SetClientMessageID sets the "client_message_id" field.
func (u *ConversationMessageUpsertOne) SetClientMessageID(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetClientMessageID(v)
	})
}

// UpdateClientMessageID sets the "client_message_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateClientMessageID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateClientMessageID()
	})
}

// SetGatewayRequestID sets the "gateway_request_id" field.
func (u *ConversationMessageUpsertOne) SetGatewayRequestID(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetGatewayRequestID(v)
	})
}

// UpdateGatewayRequestID sets the "gateway_request_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateGatewayRequestID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateGatewayRequestID()
	})
}

// ClearGatewayRequestID clears the value of the "gateway_request_id" field.
func (u *ConversationMessageUpsertOne) ClearGatewayRequestID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearGatewayRequestID()
	})
}

// Exec executes the query.
func (u *ConversationMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConversationMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConversationMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConversationMessageCreateBulk is the builder for creating many ConversationMessage entities in bulk.
type ConversationMessageCreateBulk struct {
	config
	err      error
	builders []*ConversationMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the ConversationMessage entities in the database.
func (_c *ConversationMessageCreateBulk) Save(ctx context.Context) ([]*ConversationMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConversationMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationMessageCreateBulk) SaveX(ctx context.Context) []*ConversationMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConversationMessageUpsertBulk {
	_c.conflict = opts
	return &ConversationMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationMessageCreateBulk) OnConflictColumns(columns ...string) *ConversationMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationMessageUpsertBulk{
		create: _c,
	}
}

// ConversationMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of ConversationMessage nodes.
type ConversationMessageUpsertBulk struct {
	create *ConversationMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationMessageUpsertBulk) UpdateNewValues() *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(conversationmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConversationMessageUpsertBulk) Ignore() *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationMessageUpsertBulk) DoNothing() *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationMessageCreateBulk.OnConflict
// documentation for more info.
func (u *ConversationMessageUpsertBulk) Update(set func(*ConversationMessageUpsert)) *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ConversationMessageUpsertBulk) SetConversationID(v int64) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateConversationID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ConversationMessageUpsertBulk) SetUserID(v int64) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateUserID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *ConversationMessageUpsertBulk) SetRole(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateRole() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *ConversationMessageUpsertBulk) SetContent(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateContent() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateContent()
	})
}

// SetModel sets the "model" field.
func (u *ConversationMessageUpsertBulk) SetModel(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateModel() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateModel()
	})
}

// SetStatus sets the "status" field.
func (u *ConversationMessageUpsertBulk) SetStatus(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateStatus() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetReportedInputTokens sets the "reported_input_tokens" field.
func (u *ConversationMessageUpsertBulk) SetReportedInputTokens(v int) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetReportedInputTokens(v)
	})
}

// AddReportedInputTokens adds v to the "reported_input_tokens" field.
func (u *ConversationMessageUpsertBulk) AddReportedInputTokens(v int) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.AddReportedInputTokens(v)
	})
}

// UpdateReportedInputTokens sets the "reported_input_tokens" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateReportedInputTokens() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateReportedInputTokens()
	})
}

// ClearReportedInputTokens clears the value of the "reported_input_tokens" field.
func (u *ConversationMessageUpsertBulk) ClearReportedInputTokens() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearReportedInputTokens()
	})
}

// SetReportedOutputTokens sets the "reported_output_tokens" field.
func (u *ConversationMessageUpsertBulk) SetReportedOutputTokens(v int) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetReportedOutputTokens(v)
	})
}

// AddReportedOutputTokens adds v to the "reported_output_tokens" field.
func (u *ConversationMessageUpsertBulk) AddReportedOutputTokens(v int) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.AddReportedOutputTokens(v)
	})
}

// UpdateReportedOutputTokens sets the "reported_output_tokens" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateReportedOutputTokens() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateReportedOutputTokens()
	})
}

// ClearReportedOutputTokens clears the value of the "reported_output_tokens" field.
func (u *ConversationMessageUpsertBulk) ClearReportedOutputTokens() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearReportedOutputTokens()
	})
}

// SetClientMessageID sets the "client_message_id" field.
func (u *ConversationMessageUpsertBulk) SetClientMessageID(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetClientMessageID(v)
	})
}

// UpdateClientMessageID sets the "client_message_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateClientMessageID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateClientMessageID()
	})
}

// SetGatewayRequestID sets the "gateway_request_id" field.
func (u *ConversationMessageUpsertBulk) SetGatewayRequestID(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetGatewayRequestID(v)
	})
}

// UpdateGatewayRequestID sets the "gateway_request_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateGatewayRequestID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateGatewayRequestID()
	})
}

// ClearGatewayRequestID clears the value of the "gateway_request_id" field.
func (u *ConversationMessageUpsertBulk) ClearGatewayRequestID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearGatewayRequestID()
	})
}

// Exec executes the query.
func (u *ConversationMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConversationMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
