// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationMessageUpdate is the builder for updating ConversationMessage entities.
type ConversationMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMessageMutation
}

// Where appends a list predicates to the ConversationMessageUpdate builder.
func (_u *ConversationMessageUpdate) Where(ps ...predicate.ConversationMessage) *ConversationMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMessageUpdate) SetConversationID(v int64) *ConversationMessageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableConversationID(v *int64) *ConversationMessageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ConversationMessageUpdate) SetUserID(v int64) *ConversationMessageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableUserID(v *int64) *ConversationMessageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ConversationMessageUpdate) SetRole(v string) *ConversationMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableRole(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConversationMessageUpdate) SetContent(v string) *ConversationMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableContent(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ConversationMessageUpdate) SetModel(v string) *ConversationMessageUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableModel(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationMessageUpdate) SetStatus(v string) *ConversationMessageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableStatus(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReportedInputTokens sets the "reported_input_tokens" field.
func (_u *ConversationMessageUpdate) SetReportedInputTokens(v int) *ConversationMessageUpdate {
	_u.mutation.ResetReportedInputTokens()
	_u.mutation.SetReportedInputTokens(v)
	return _u
}

// SetNillableReportedInputTokens sets the "reported_input_tokens" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableReportedInputTokens(v *int) *ConversationMessageUpdate {
	if v != nil {
		_u.SetReportedInputTokens(*v)
	}
	return _u
}

// AddReportedInputTokens adds value to the "reported_input_tokens" field.
func (_u *ConversationMessageUpdate) AddReportedInputTokens(v int) *ConversationMessageUpdate {
	_u.mutation.AddReportedInputTokens(v)
	return _u
}

// ClearReportedInputTokens clears the value of the "reported_input_tokens" field.
func (_u *ConversationMessageUpdate) ClearReportedInputTokens() *ConversationMessageUpdate {
	_u.mutation.ClearReportedInputTokens()
	return _u
}

// SetReportedOutputTokens sets the "reported_output_tokens" field.
func (_u *ConversationMessageUpdate) SetReportedOutputTokens(v int) *ConversationMessageUpdate {
	_u.mutation.ResetReportedOutputTokens()
	_u.mutation.SetReportedOutputTokens(v)
	return _u
}

// SetNillableReportedOutputTokens sets the "reported_output_tokens" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableReportedOutputTokens(v *int) *ConversationMessageUpdate {
	if v != nil {
		_u.SetReportedOutputTokens(*v)
	}
	return _u
}

// AddReportedOutputTokens adds value to the "reported_output_tokens" field.
func (_u *ConversationMessageUpdate) AddReportedOutputTokens(v int) *ConversationMessageUpdate {
	_u.mutation.AddReportedOutputTokens(v)
	return _u
}

// ClearReportedOutputTokens clears the value of the "reported_output_tokens" field.
func (_u *ConversationMessageUpdate) ClearReportedOutputTokens() *ConversationMessageUpdate {
	_u.mutation.ClearReportedOutputTokens()
	return _u
}

// SetClientMessageID sets the "client_message_id" field.
func (_u *ConversationMessageUpdate) SetClientMessageID(v string) *ConversationMessageUpdate {
	_u.mutation.SetClientMessageID(v)
	return _u
}

// SetNillableClientMessageID sets the "client_message_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableClientMessageID(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetClientMessageID(*v)
	}
	return _u
}

// SetGatewayRequestID sets the "gateway_request_id" field.
func (_u *ConversationMessageUpdate) SetGatewayRequestID(v string) *ConversationMessageUpdate {
	_u.mutation.SetGatewayRequestID(v)
	return _u
}

// SetNillableGatewayRequestID sets the "gateway_request_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableGatewayRequestID(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetGatewayRequestID(*v)
	}
	return _u
}

// ClearGatewayRequestID clears the value of the "gateway_request_id" field.
func (_u *ConversationMessageUpdate) ClearGatewayRequestID() *ConversationMessageUpdate {
	_u.mutation.ClearGatewayRequestID()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdate) SetConversation(v *Conversation) *ConversationMessageUpdate {
	return _u.SetConversationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ConversationMessageUpdate) SetUser(v *User) *ConversationMessageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_u *ConversationMessageUpdate) Mutation() *ConversationMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdate) ClearConversation() *ConversationMessageUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ConversationMessageUpdate) ClearUser() *ConversationMessageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationMessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := conversationmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := conversationmessage.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := conversationmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientMessageID(); ok {
		if err := conversationmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.client_message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayRequestID(); ok {
		if err := conversationmessage.GatewayRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "gateway_request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.gateway_request_id": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.conversation"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.user"`)
	}
	return nil
}

func (_u *ConversationMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationmessage.Table, conversationmessage.Columns, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(conversationmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(conversationmessage.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversationmessage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReportedInputTokens(); ok {
		_spec.SetField(conversationmessage.FieldReportedInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReportedInputTokens(); ok {
		_spec.AddField(conversationmessage.FieldReportedInputTokens, field.TypeInt, value)
	}
	if _u.mutation.ReportedInputTokensCleared() {
		_spec.ClearField(conversationmessage.FieldReportedInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.ReportedOutputTokens(); ok {
		_spec.SetField(conversationmessage.FieldReportedOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReportedOutputTokens(); ok {
		_spec.AddField(conversationmessage.FieldReportedOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.ReportedOutputTokensCleared() {
		_spec.ClearField(conversationmessage.FieldReportedOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.ClientMessageID(); ok {
		_spec.SetField(conversationmessage.FieldClientMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayRequestID(); ok {
		_spec.SetField(conversationmessage.FieldGatewayRequestID, field.TypeString, value)
	}
	if _u.mutation.GatewayRequestIDCleared() {
		_spec.ClearField(conversationmessage.FieldGatewayRequestID, field.TypeString)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.UserTable,
			Columns: []string{conversationmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.UserTable,
			Columns: []string{conversationmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationMessageUpdateOne is the builder for updating a single ConversationMessage entity.
type ConversationMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMessageMutation
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMessageUpdateOne) SetConversationID(v int64) *ConversationMessageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableConversationID(v *int64) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ConversationMessageUpdateOne) SetUserID(v int64) *ConversationMessageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableUserID(v *int64) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ConversationMessageUpdateOne) SetRole(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableRole(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConversationMessageUpdateOne) SetContent(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableContent(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ConversationMessageUpdateOne) SetModel(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableModel(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationMessageUpdateOne) SetStatus(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableStatus(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReportedInputTokens sets the "reported_input_tokens" field.
func (_u *ConversationMessageUpdateOne) SetReportedInputTokens(v int) *ConversationMessageUpdateOne {
	_u.mutation.ResetReportedInputTokens()
	_u.mutation.SetReportedInputTokens(v)
	return _u
}

// SetNillableReportedInputTokens sets the "reported_input_tokens" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableReportedInputTokens(v *int) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetReportedInputTokens(*v)
	}
	return _u
}

// AddReportedInputTokens adds value to the "reported_input_tokens" field.
func (_u *ConversationMessageUpdateOne) AddReportedInputTokens(v int) *ConversationMessageUpdateOne {
	_u.mutation.AddReportedInputTokens(v)
	return _u
}

// ClearReportedInputTokens clears the value of the "reported_input_tokens" field.
func (_u *ConversationMessageUpdateOne) ClearReportedInputTokens() *ConversationMessageUpdateOne {
	_u.mutation.ClearReportedInputTokens()
	return _u
}

// SetReportedOutputTokens sets the "reported_output_tokens" field.
func (_u *ConversationMessageUpdateOne) SetReportedOutputTokens(v int) *ConversationMessageUpdateOne {
	_u.mutation.ResetReportedOutputTokens()
	_u.mutation.SetReportedOutputTokens(v)
	return _u
}

// SetNillableReportedOutputTokens sets the "reported_output_tokens" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableReportedOutputTokens(v *int) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetReportedOutputTokens(*v)
	}
	return _u
}

// AddReportedOutputTokens adds value to the "reported_output_tokens" field.
func (_u *ConversationMessageUpdateOne) AddReportedOutputTokens(v int) *ConversationMessageUpdateOne {
	_u.mutation.AddReportedOutputTokens(v)
	return _u
}

// ClearReportedOutputTokens clears the value of the "reported_output_tokens" field.
func (_u *ConversationMessageUpdateOne) ClearReportedOutputTokens() *ConversationMessageUpdateOne {
	_u.mutation.ClearReportedOutputTokens()
	return _u
}

// SetClientMessageID sets the "client_message_id" field.
func (_u *ConversationMessageUpdateOne) SetClientMessageID(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetClientMessageID(v)
	return _u
}

// SetNillableClientMessageID sets the "client_message_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableClientMessageID(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetClientMessageID(*v)
	}
	return _u
}

// SetGatewayRequestID sets the "gateway_request_id" field.
func (_u *ConversationMessageUpdateOne) SetGatewayRequestID(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetGatewayRequestID(v)
	return _u
}

// SetNillableGatewayRequestID sets the "gateway_request_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableGatewayRequestID(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetGatewayRequestID(*v)
	}
	return _u
}

// ClearGatewayRequestID clears the value of the "gateway_request_id" field.
func (_u *ConversationMessageUpdateOne) ClearGatewayRequestID() *ConversationMessageUpdateOne {
	_u.mutation.ClearGatewayRequestID()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdateOne) SetConversation(v *Conversation) *ConversationMessageUpdateOne {
	return _u.SetConversationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ConversationMessageUpdateOne) SetUser(v *User) *ConversationMessageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_u *ConversationMessageUpdateOne) Mutation() *ConversationMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdateOne) ClearConversation() *ConversationMessageUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ConversationMessageUpdateOne) ClearUser() *ConversationMessageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ConversationMessageUpdate builder.
func (_u *ConversationMessageUpdateOne) Where(ps ...predicate.ConversationMessage) *ConversationMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationMessageUpdateOne) Select(field string, fields ...string) *ConversationMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConversationMessage entity.
func (_u *ConversationMessageUpdateOne) Save(ctx context.Context) (*ConversationMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMessageUpdateOne) SaveX(ctx context.Context) *ConversationMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := conversationmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := conversationmessage.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := conversationmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientMessageID(); ok {
		if err := conversationmessage.ClientMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "client_message_id", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.client_message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayRequestID(); ok {
		if err := conversationmessage.GatewayRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "gateway_request_id", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.gateway_request_id": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.conversation"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.user"`)
	}
	return nil
}

func (_u *ConversationMessageUpdateOne) sqlSave(ctx context.Context) (_node *ConversationMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationmessage.Table, conversationmessage.Columns, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConversationMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversationmessage.FieldID)
		for _, f := range fields {
			if !conversationmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversationmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(conversationmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(conversationmessage.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversationmessage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReportedInputTokens(); ok {
		_spec.SetField(conversationmessage.FieldReportedInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReportedInputTokens(); ok {
		_spec.AddField(conversationmessage.FieldReportedInputTokens, field.TypeInt, value)
	}
	if _u.mutation.ReportedInputTokensCleared() {
		_spec.ClearField(conversationmessage.FieldReportedInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.ReportedOutputTokens(); ok {
		_spec.SetField(conversationmessage.FieldReportedOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReportedOutputTokens(); ok {
		_spec.AddField(conversationmessage.FieldReportedOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.ReportedOutputTokensCleared() {
		_spec.ClearField(conversationmessage.FieldReportedOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.ClientMessageID(); ok {
		_spec.SetField(conversationmessage.FieldClientMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayRequestID(); ok {
		_spec.SetField(conversationmessage.FieldGatewayRequestID, field.TypeString, value)
	}
	if _u.mutation.GatewayRequestIDCleared() {
		_spec.ClearField(conversationmessage.FieldGatewayRequestID, field.TypeString)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.UserTable,
			Columns: []string{conversationmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.UserTable,
			Columns: []string{conversationmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConversationMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
