// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paygorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaygOrderCreate is the builder for creating a PaygOrder entity.
type PaygOrderCreate struct {
	config
	mutation *PaygOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaygOrderCreate) SetCreatedAt(v time.Time) *PaygOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaygOrderCreate) SetNillableCreatedAt(v *time.Time) *PaygOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaygOrderCreate) SetUpdatedAt(v time.Time) *PaygOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaygOrderCreate) SetNillableUpdatedAt(v *time.Time) *PaygOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaygOrderCreate) SetUserID(v int64) *PaygOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetClientSn sets the "client_sn" field.
func (_c *PaygOrderCreate) SetClientSn(v string) *PaygOrderCreate {
	_c.mutation.SetClientSn(v)
	return _c
}

// SetSn sets the "sn" field.
func (_c *PaygOrderCreate) SetSn(v string) *PaygOrderCreate {
	_c.mutation.SetSn(v)
	return _c
}

// SetNillableSn sets the "sn" field if the given value is not nil.
func (_c *PaygOrderCreate) SetNillableSn(v *string) *PaygOrderCreate {
	if v != nil {
		_c.SetSn(*v)
	}
	return _c
}

// SetAmountYuan sets the "amount_yuan" field.
func (_c *PaygOrderCreate) SetAmountYuan(v float64) *PaygOrderCreate {
	_c.mutation.SetAmountYuan(v)
	return _c
}

// SetAmountCent sets the "amount_cent" field.
func (_c *PaygOrderCreate) SetAmountCent(v int64) *PaygOrderCreate {
	_c.mutation.SetAmountCent(v)
	return _c
}

// SetCreditAmount sets the "credit_amount" field.
func (_c *PaygOrderCreate) SetCreditAmount(v float64) *PaygOrderCreate {
	_c.mutation.SetCreditAmount(v)
	return _c
}

// SetPayway sets the "payway" field.
func (_c *PaygOrderCreate) SetPayway(v string) *PaygOrderCreate {
	_c.mutation.SetPayway(v)
	return _c
}

// SetNillablePayway sets the "payway" field if the given value is not nil.
func (_c *PaygOrderCreate) SetNillablePayway(v *string) *PaygOrderCreate {
	if v != nil {
		_c.SetPayway(*v)
	}
	return _c
}

// SetPaywayName sets the "payway_name" field.
func (_c *PaygOrderCreate) SetPaywayName(v string) *PaygOrderCreate {
	_c.mutation.SetPaywayName(v)
	return _c
}

// SetNillablePaywayName sets the "payway_name" field if the given value is not nil.
func (_c *PaygOrderCreate) SetNillablePaywayName(v *string) *PaygOrderCreate {
	if v != nil {
		_c.SetPaywayName(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaygOrderCreate) SetStatus(v string) *PaygOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaygOrderCreate) SetNillableStatus(v *string) *PaygOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaygOrderCreate) SetPaidAt(v time.Time) *PaygOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaygOrderCreate) SetNillablePaidAt(v *time.Time) *PaygOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaygOrderCreate) SetUser(v *User) *PaygOrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaygOrderMutation object of the builder.
func (_c *PaygOrderCreate) Mutation() *PaygOrderMutation {
	return _c.mutation
}

// Save creates the PaygOrder in the database.
func (_c *PaygOrderCreate) Save(ctx context.Context) (*PaygOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaygOrderCreate) SaveX(ctx context.Context) *PaygOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaygOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaygOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaygOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paygorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paygorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Payway(); !ok {
		v := paygorder.DefaultPayway
		_c.mutation.SetPayway(v)
	}
	if _, ok := _c.mutation.PaywayName(); !ok {
		v := paygorder.DefaultPaywayName
		_c.mutation.SetPaywayName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paygorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaygOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaygOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaygOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaygOrder.user_id"`)}
	}
	if _, ok := _c.mutation.ClientSn(); !ok {
		return &ValidationError{Name: "client_sn", err: errors.New(`ent: missing required field "PaygOrder.client_sn"`)}
	}
	if v, ok := _c.mutation.ClientSn(); ok {
		if err := paygorder.ClientSnValidator(v); err != nil {
			return &ValidationError{Name: "client_sn", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.client_sn": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Sn(); ok {
		if err := paygorder.SnValidator(v); err != nil {
			return &ValidationError{Name: "sn", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.sn": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountYuan(); !ok {
		return &ValidationError{Name: "amount_yuan", err: errors.New(`ent: missing required field "PaygOrder.amount_yuan"`)}
	}
	if _, ok := _c.mutation.AmountCent(); !ok {
		return &ValidationError{Name: "amount_cent", err: errors.New(`ent: missing required field "PaygOrder.amount_cent"`)}
	}
	if _, ok := _c.mutation.CreditAmount(); !ok {
		return &ValidationError{Name: "credit_amount", err: errors.New(`ent: missing required field "PaygOrder.credit_amount"`)}
	}
	if _, ok := _c.mutation.Payway(); !ok {
		return &ValidationError{Name: "payway", err: errors.New(`ent: missing required field "PaygOrder.payway"`)}
	}
	if v, ok := _c.mutation.Payway(); ok {
		if err := paygorder.PaywayValidator(v); err != nil {
			return &ValidationError{Name: "payway", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.payway": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaywayName(); !ok {
		return &ValidationError{Name: "payway_name", err: errors.New(`ent: missing required field "PaygOrder.payway_name"`)}
	}
	if v, ok := _c.mutation.PaywayName(); ok {
		if err := paygorder.PaywayNameValidator(v); err != nil {
			return &ValidationError{Name: "payway_name", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.payway_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaygOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paygorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaygOrder.user"`)}
	}
	return nil
}

func (_c *PaygOrderCreate) sqlSave(ctx context.Context) (*PaygOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaygOrderCreate) createSpec() (*PaygOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaygOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paygorder.Table, sqlgraph.NewFieldSpec(paygorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paygorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paygorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientSn(); ok {
		_spec.SetField(paygorder.FieldClientSn, field.TypeString, value)
		_node.ClientSn = value
	}
	if value, ok := _c.mutation.Sn(); ok {
		_spec.SetField(paygorder.FieldSn, field.TypeString, value)
		_node.Sn = &value
	}
	if value, ok := _c.mutation.AmountYuan(); ok {
		_spec.SetField(paygorder.FieldAmountYuan, field.TypeFloat64, value)
		_node.AmountYuan = value
	}
	if value, ok := _c.mutation.AmountCent(); ok {
		_spec.SetField(paygorder.FieldAmountCent, field.TypeInt64, value)
		_node.AmountCent = value
	}
	if value, ok := _c.mutation.CreditAmount(); ok {
		_spec.SetField(paygorder.FieldCreditAmount, field.TypeFloat64, value)
		_node.CreditAmount = value
	}
	if value, ok := _c.mutation.Payway(); ok {
		_spec.SetField(paygorder.FieldPayway, field.TypeString, value)
		_node.Payway = value
	}
	if value, ok := _c.mutation.PaywayName(); ok {
		_spec.SetField(paygorder.FieldPaywayName, field.TypeString, value)
		_node.PaywayName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paygorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paygorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paygorder.UserTable,
			Columns: []string{paygorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaygOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaygOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaygOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaygOrderUpsertOne {
	_c.conflict = opts
	return &PaygOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaygOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaygOrderCreate) OnConflictColumns(columns ...string) *PaygOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaygOrderUpsertOne{
		create: _c,
	}
}

type (
	// PaygOrderUpsertOne is the builder for "upsert"-ing
	//  one PaygOrder node.
	PaygOrderUpsertOne struct {
		create *PaygOrderCreate
	}

	// PaygOrderUpsert is the "OnConflict" setter.
	PaygOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaygOrderUpsert) SetUpdatedAt(v time.Time) *PaygOrderUpsert {
	u.Set(paygorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateUpdatedAt() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaygOrderUpsert) SetUserID(v int64) *PaygOrderUpsert {
	u.Set(paygorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateUserID() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldUserID)
	return u
}

// SetClientSn sets the "client_sn" field.
func (u *PaygOrderUpsert) SetClientSn(v string) *PaygOrderUpsert {
	u.Set(paygorder.FieldClientSn, v)
	return u
}

// UpdateClientSn sets the "client_sn" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateClientSn() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldClientSn)
	return u
}

// SetSn sets the "sn" field.
func (u *PaygOrderUpsert) SetSn(v string) *PaygOrderUpsert {
	u.Set(paygorder.FieldSn, v)
	return u
}

// UpdateSn sets the "sn" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateSn() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldSn)
	return u
}

// ClearSn clears the value of the "sn" field.
func (u *PaygOrderUpsert) ClearSn() *PaygOrderUpsert {
	u.SetNull(paygorder.FieldSn)
	return u
}

// SetAmountYuan sets the "amount_yuan" field.
func (u *PaygOrderUpsert) SetAmountYuan(v float64) *PaygOrderUpsert {
	u.Set(paygorder.FieldAmountYuan, v)
	return u
}

// UpdateAmountYuan sets the "amount_yuan" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateAmountYuan() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldAmountYuan)
	return u
}

// AddAmountYuan adds v to the "amount_yuan" field.
func (u *PaygOrderUpsert) AddAmountYuan(v float64) *PaygOrderUpsert {
	u.Add(paygorder.FieldAmountYuan, v)
	return u
}

// SetAmountCent sets the "amount_cent" field.
func (u *PaygOrderUpsert) SetAmountCent(v int64) *PaygOrderUpsert {
	u.Set(paygorder.FieldAmountCent, v)
	return u
}

// UpdateAmountCent sets the "amount_cent" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateAmountCent() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldAmountCent)
	return u
}

// AddAmountCent adds v to the "amount_cent" field.
func (u *PaygOrderUpsert) AddAmountCent(v int64) *PaygOrderUpsert {
	u.Add(paygorder.FieldAmountCent, v)
	return u
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaygOrderUpsert) SetCreditAmount(v float64) *PaygOrderUpsert {
	u.Set(paygorder.FieldCreditAmount, v)
	return u
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateCreditAmount() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldCreditAmount)
	return u
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaygOrderUpsert) AddCreditAmount(v float64) *PaygOrderUpsert {
	u.Add(paygorder.FieldCreditAmount, v)
	return u
}

// SetPayway sets the "payway" field.
func (u *PaygOrderUpsert) SetPayway(v string) *PaygOrderUpsert {
	u.Set(paygorder.FieldPayway, v)
	return u
}

// UpdatePayway sets the "payway" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdatePayway() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldPayway)
	return u
}

// SetPaywayName sets the "payway_name" field.
func (u *PaygOrderUpsert) SetPaywayName(v string) *PaygOrderUpsert {
	u.Set(paygorder.FieldPaywayName, v)
	return u
}

// UpdatePaywayName sets the "payway_name" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdatePaywayName() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldPaywayName)
	return u
}

// SetStatus sets the "status" field.
func (u *PaygOrderUpsert) SetStatus(v string) *PaygOrderUpsert {
	u.Set(paygorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdateStatus() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldStatus)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *PaygOrderUpsert) SetPaidAt(v time.Time) *PaygOrderUpsert {
	u.Set(paygorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaygOrderUpsert) UpdatePaidAt() *PaygOrderUpsert {
	u.SetExcluded(paygorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaygOrderUpsert) ClearPaidAt() *PaygOrderUpsert {
	u.SetNull(paygorder.FieldPaidAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaygOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaygOrderUpsertOne) UpdateNewValues() *PaygOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paygorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaygOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaygOrderUpsertOne) Ignore() *PaygOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaygOrderUpsertOne) DoNothing() *PaygOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaygOrderCreate.OnConflict
// documentation for more info.
func (u *PaygOrderUpsertOne) Update(set func(*PaygOrderUpsert)) *PaygOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaygOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaygOrderUpsertOne) SetUpdatedAt(v time.Time) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateUpdatedAt() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaygOrderUpsertOne) SetUserID(v int64) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateUserID() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetClientSn sets the "client_sn" field.
func (u *PaygOrderUpsertOne) SetClientSn(v string) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetClientSn(v)
	})
}

// UpdateClientSn sets the "client_sn" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateClientSn() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateClientSn()
	})
}

// SetSn sets the "sn" field.
func (u *PaygOrderUpsertOne) SetSn(v string) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetSn(v)
	})
}

// UpdateSn sets the "sn" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateSn() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateSn()
	})
}

// ClearSn clears the value of the "sn" field.
func (u *PaygOrderUpsertOne) ClearSn() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.ClearSn()
	})
}

// SetAmountYuan sets the "amount_yuan" field.
func (u *PaygOrderUpsertOne) SetAmountYuan(v float64) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetAmountYuan(v)
	})
}

// AddAmountYuan adds v to the "amount_yuan" field.
func (u *PaygOrderUpsertOne) AddAmountYuan(v float64) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.AddAmountYuan(v)
	})
}

// UpdateAmountYuan sets the "amount_yuan" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateAmountYuan() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateAmountYuan()
	})
}

// SetAmountCent sets the "amount_cent" field.
func (u *PaygOrderUpsertOne) SetAmountCent(v int64) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetAmountCent(v)
	})
}

// AddAmountCent adds v to the "amount_cent" field.
func (u *PaygOrderUpsertOne) AddAmountCent(v int64) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.AddAmountCent(v)
	})
}

// UpdateAmountCent sets the "amount_cent" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateAmountCent() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateAmountCent()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaygOrderUpsertOne) SetCreditAmount(v float64) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaygOrderUpsertOne) AddCreditAmount(v float64) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateCreditAmount() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateCreditAmount()
	})
}

// SetPayway sets the "payway" field.
func (u *PaygOrderUpsertOne) SetPayway(v string) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetPayway(v)
	})
}

// UpdatePayway sets the "payway" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdatePayway() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdatePayway()
	})
}

// SetPaywayName sets the "payway_name" field.
func (u *PaygOrderUpsertOne) SetPaywayName(v string) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetPaywayName(v)
	})
}

// UpdatePaywayName sets the "payway_name" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdatePaywayName() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdatePaywayName()
	})
}

// SetStatus sets the "status" field.
func (u *PaygOrderUpsertOne) SetStatus(v string) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdateStatus() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaygOrderUpsertOne) SetPaidAt(v time.Time) *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaygOrderUpsertOne) UpdatePaidAt() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaygOrderUpsertOne) ClearPaidAt() *PaygOrderUpsertOne {
	return u.Update(func(s *PaygOrderUpsert) {
		s.ClearPaidAt()
	})
}

// Exec executes the query.
func (u *PaygOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaygOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaygOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaygOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaygOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaygOrderCreateBulk is the builder for creating many PaygOrder entities in bulk.
type PaygOrderCreateBulk struct {
	config
	err      error
	builders []*PaygOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaygOrder entities in the database.
func (_c *PaygOrderCreateBulk) Save(ctx context.Context) ([]*PaygOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaygOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaygOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaygOrderCreateBulk) SaveX(ctx context.Context) []*PaygOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaygOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaygOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaygOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaygOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaygOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaygOrderUpsertBulk {
	_c.conflict = opts
	return &PaygOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaygOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaygOrderCreateBulk) OnConflictColumns(columns ...string) *PaygOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaygOrderUpsertBulk{
		create: _c,
	}
}

// PaygOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaygOrder nodes.
type PaygOrderUpsertBulk struct {
	create *PaygOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaygOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaygOrderUpsertBulk) UpdateNewValues() *PaygOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paygorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaygOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaygOrderUpsertBulk) Ignore() *PaygOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaygOrderUpsertBulk) DoNothing() *PaygOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaygOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaygOrderUpsertBulk) Update(set func(*PaygOrderUpsert)) *PaygOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaygOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaygOrderUpsertBulk) SetUpdatedAt(v time.Time) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateUpdatedAt() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaygOrderUpsertBulk) SetUserID(v int64) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateUserID() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetClientSn sets the "client_sn" field.
func (u *PaygOrderUpsertBulk) SetClientSn(v string) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetClientSn(v)
	})
}

// UpdateClientSn sets the "client_sn" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateClientSn() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateClientSn()
	})
}

// SetSn sets the "sn" field.
func (u *PaygOrderUpsertBulk) SetSn(v string) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetSn(v)
	})
}

// UpdateSn sets the "sn" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateSn() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateSn()
	})
}

// ClearSn clears the value of the "sn" field.
func (u *PaygOrderUpsertBulk) ClearSn() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.ClearSn()
	})
}

// SetAmountYuan sets the "amount_yuan" field.
func (u *PaygOrderUpsertBulk) SetAmountYuan(v float64) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetAmountYuan(v)
	})
}

// AddAmountYuan adds v to the "amount_yuan" field.
func (u *PaygOrderUpsertBulk) AddAmountYuan(v float64) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.AddAmountYuan(v)
	})
}

// UpdateAmountYuan sets the "amount_yuan" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateAmountYuan() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateAmountYuan()
	})
}

// SetAmountCent sets the "amount_cent" field.
func (u *PaygOrderUpsertBulk) SetAmountCent(v int64) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetAmountCent(v)
	})
}

// AddAmountCent adds v to the "amount_cent" field.
func (u *PaygOrderUpsertBulk) AddAmountCent(v int64) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.AddAmountCent(v)
	})
}

// UpdateAmountCent sets the "amount_cent" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateAmountCent() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateAmountCent()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaygOrderUpsertBulk) SetCreditAmount(v float64) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaygOrderUpsertBulk) AddCreditAmount(v float64) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateCreditAmount() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateCreditAmount()
	})
}

// SetPayway sets the "payway" field.
func (u *PaygOrderUpsertBulk) SetPayway(v string) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetPayway(v)
	})
}

// UpdatePayway sets the "payway" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdatePayway() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdatePayway()
	})
}

// SetPaywayName sets the "payway_name" field.
func (u *PaygOrderUpsertBulk) SetPaywayName(v string) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetPaywayName(v)
	})
}

// UpdatePaywayName sets the "payway_name" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdatePaywayName() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdatePaywayName()
	})
}

// SetStatus sets the "status" field.
func (u *PaygOrderUpsertBulk) SetStatus(v string) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdateStatus() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaygOrderUpsertBulk) SetPaidAt(v time.Time) *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaygOrderUpsertBulk) UpdatePaidAt() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaygOrderUpsertBulk) ClearPaidAt() *PaygOrderUpsertBulk {
	return u.Update(func(s *PaygOrderUpsert) {
		s.ClearPaidAt()
	})
}

// Exec executes the query.
func (u *PaygOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaygOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaygOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaygOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
