// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paygorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaygOrder is the model entity for the PaygOrder schema.
type PaygOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ClientSn holds the value of the "client_sn" field.
	ClientSn string `json:"client_sn,omitempty"`
	// Sn holds the value of the "sn" field.
	Sn *string `json:"sn,omitempty"`
	// AmountYuan holds the value of the "amount_yuan" field.
	AmountYuan float64 `json:"amount_yuan,omitempty"`
	// AmountCent holds the value of the "amount_cent" field.
	AmountCent int64 `json:"amount_cent,omitempty"`
	// CreditAmount holds the value of the "credit_amount" field.
	CreditAmount float64 `json:"credit_amount,omitempty"`
	// Payway holds the value of the "payway" field.
	Payway string `json:"payway,omitempty"`
	// PaywayName holds the value of the "payway_name" field.
	PaywayName string `json:"payway_name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaygOrderQuery when eager-loading is set.
	Edges        PaygOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaygOrderEdges holds the relations/edges for other nodes in the graph.
type PaygOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaygOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaygOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paygorder.FieldAmountYuan, paygorder.FieldCreditAmount:
			values[i] = new(sql.NullFloat64)
		case paygorder.FieldID, paygorder.FieldUserID, paygorder.FieldAmountCent:
			values[i] = new(sql.NullInt64)
		case paygorder.FieldClientSn, paygorder.FieldSn, paygorder.FieldPayway, paygorder.FieldPaywayName, paygorder.FieldStatus:
			values[i] = new(sql.NullString)
		case paygorder.FieldCreatedAt, paygorder.FieldUpdatedAt, paygorder.FieldPaidAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaygOrder fields.
func (_m *PaygOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paygorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paygorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paygorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case paygorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case paygorder.FieldClientSn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_sn", values[i])
			} else if value.Valid {
				_m.ClientSn = value.String
			}
		case paygorder.FieldSn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sn", values[i])
			} else if value.Valid {
				_m.Sn = new(string)
				*_m.Sn = value.String
			}
		case paygorder.FieldAmountYuan:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_yuan", values[i])
			} else if value.Valid {
				_m.AmountYuan = value.Float64
			}
		case paygorder.FieldAmountCent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cent", values[i])
			} else if value.Valid {
				_m.AmountCent = value.Int64
			}
		case paygorder.FieldCreditAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_amount", values[i])
			} else if value.Valid {
				_m.CreditAmount = value.Float64
			}
		case paygorder.FieldPayway:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payway", values[i])
			} else if value.Valid {
				_m.Payway = value.String
			}
		case paygorder.FieldPaywayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payway_name", values[i])
			} else if value.Valid {
				_m.PaywayName = value.String
			}
		case paygorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paygorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaygOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PaygOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PaygOrder entity.
func (_m *PaygOrder) QueryUser() *UserQuery {
	return NewPaygOrderClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PaygOrder.
// Note that you need to call PaygOrder.Unwrap() before calling this method if this PaygOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaygOrder) Update() *PaygOrderUpdateOne {
	return NewPaygOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaygOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaygOrder) Unwrap() *PaygOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaygOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaygOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PaygOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("client_sn=")
	builder.WriteString(_m.ClientSn)
	builder.WriteString(", ")
	if v := _m.Sn; v != nil {
		builder.WriteString("sn=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount_yuan=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountYuan))
	builder.WriteString(", ")
	builder.WriteString("amount_cent=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCent))
	builder.WriteString(", ")
	builder.WriteString("credit_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditAmount))
	builder.WriteString(", ")
	builder.WriteString("payway=")
	builder.WriteString(_m.Payway)
	builder.WriteString(", ")
	builder.WriteString("payway_name=")
	builder.WriteString(_m.PaywayName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PaygOrders is a parsable slice of PaygOrder.
type PaygOrders []*PaygOrder
