// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paygorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaygOrderUpdate is the builder for updating PaygOrder entities.
type PaygOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaygOrderMutation
}

// Where appends a list predicates to the PaygOrderUpdate builder.
func (_u *PaygOrderUpdate) Where(ps ...predicate.PaygOrder) *PaygOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaygOrderUpdate) SetUpdatedAt(v time.Time) *PaygOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaygOrderUpdate) SetUserID(v int64) *PaygOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillableUserID(v *int64) *PaygOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientSn sets the "client_sn" field.
func (_u *PaygOrderUpdate) SetClientSn(v string) *PaygOrderUpdate {
	_u.mutation.SetClientSn(v)
	return _u
}

// SetNillableClientSn sets the "client_sn" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillableClientSn(v *string) *PaygOrderUpdate {
	if v != nil {
		_u.SetClientSn(*v)
	}
	return _u
}

// SetSn sets the "sn" field.
func (_u *PaygOrderUpdate) SetSn(v string) *PaygOrderUpdate {
	_u.mutation.SetSn(v)
	return _u
}

// SetNillableSn sets the "sn" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillableSn(v *string) *PaygOrderUpdate {
	if v != nil {
		_u.SetSn(*v)
	}
	return _u
}

// ClearSn clears the value of the "sn" field.
func (_u *PaygOrderUpdate) ClearSn() *PaygOrderUpdate {
	_u.mutation.ClearSn()
	return _u
}

// SetAmountYuan sets the "amount_yuan" field.
func (_u *PaygOrderUpdate) SetAmountYuan(v float64) *PaygOrderUpdate {
	_u.mutation.ResetAmountYuan()
	_u.mutation.SetAmountYuan(v)
	return _u
}

// SetNillableAmountYuan sets the "amount_yuan" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillableAmountYuan(v *float64) *PaygOrderUpdate {
	if v != nil {
		_u.SetAmountYuan(*v)
	}
	return _u
}

// AddAmountYuan adds value to the "amount_yuan" field.
func (_u *PaygOrderUpdate) AddAmountYuan(v float64) *PaygOrderUpdate {
	_u.mutation.AddAmountYuan(v)
	return _u
}

// SetAmountCent sets the "amount_cent" field.
func (_u *PaygOrderUpdate) SetAmountCent(v int64) *PaygOrderUpdate {
	_u.mutation.ResetAmountCent()
	_u.mutation.SetAmountCent(v)
	return _u
}

// SetNillableAmountCent sets the "amount_cent" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillableAmountCent(v *int64) *PaygOrderUpdate {
	if v != nil {
		_u.SetAmountCent(*v)
	}
	return _u
}

// AddAmountCent adds value to the "amount_cent" field.
func (_u *PaygOrderUpdate) AddAmountCent(v int64) *PaygOrderUpdate {
	_u.mutation.AddAmountCent(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *PaygOrderUpdate) SetCreditAmount(v float64) *PaygOrderUpdate {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillableCreditAmount(v *float64) *PaygOrderUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *PaygOrderUpdate) AddCreditAmount(v float64) *PaygOrderUpdate {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetPayway sets the "payway" field.
func (_u *PaygOrderUpdate) SetPayway(v string) *PaygOrderUpdate {
	_u.mutation.SetPayway(v)
	return _u
}

// SetNillablePayway sets the "payway" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillablePayway(v *string) *PaygOrderUpdate {
	if v != nil {
		_u.SetPayway(*v)
	}
	return _u
}

// SetPaywayName sets the "payway_name" field.
func (_u *PaygOrderUpdate) SetPaywayName(v string) *PaygOrderUpdate {
	_u.mutation.SetPaywayName(v)
	return _u
}

// SetNillablePaywayName sets the "payway_name" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillablePaywayName(v *string) *PaygOrderUpdate {
	if v != nil {
		_u.SetPaywayName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaygOrderUpdate) SetStatus(v string) *PaygOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillableStatus(v *string) *PaygOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaygOrderUpdate) SetPaidAt(v time.Time) *PaygOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaygOrderUpdate) SetNillablePaidAt(v *time.Time) *PaygOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaygOrderUpdate) ClearPaidAt() *PaygOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaygOrderUpdate) SetUser(v *User) *PaygOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaygOrderMutation object of the builder.
func (_u *PaygOrderUpdate) Mutation() *PaygOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaygOrderUpdate) ClearUser() *PaygOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaygOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaygOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaygOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaygOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaygOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paygorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaygOrderUpdate) check() error {
	if v, ok := _u.mutation.ClientSn(); ok {
		if err := paygorder.ClientSnValidator(v); err != nil {
			return &ValidationError{Name: "client_sn", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.client_sn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sn(); ok {
		if err := paygorder.SnValidator(v); err != nil {
			return &ValidationError{Name: "sn", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.sn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payway(); ok {
		if err := paygorder.PaywayValidator(v); err != nil {
			return &ValidationError{Name: "payway", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.payway": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaywayName(); ok {
		if err := paygorder.PaywayNameValidator(v); err != nil {
			return &ValidationError{Name: "payway_name", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.payway_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paygorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaygOrder.user"`)
	}
	return nil
}

func (_u *PaygOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paygorder.Table, paygorder.Columns, sqlgraph.NewFieldSpec(paygorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paygorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientSn(); ok {
		_spec.SetField(paygorder.FieldClientSn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sn(); ok {
		_spec.SetField(paygorder.FieldSn, field.TypeString, value)
	}
	if _u.mutation.SnCleared() {
		_spec.ClearField(paygorder.FieldSn, field.TypeString)
	}
	if value, ok := _u.mutation.AmountYuan(); ok {
		_spec.SetField(paygorder.FieldAmountYuan, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountYuan(); ok {
		_spec.AddField(paygorder.FieldAmountYuan, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCent(); ok {
		_spec.SetField(paygorder.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCent(); ok {
		_spec.AddField(paygorder.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(paygorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(paygorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Payway(); ok {
		_spec.SetField(paygorder.FieldPayway, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaywayName(); ok {
		_spec.SetField(paygorder.FieldPaywayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paygorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paygorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paygorder.FieldPaidAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paygorder.UserTable,
			Columns: []string{paygorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paygorder.UserTable,
			Columns: []string{paygorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paygorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaygOrderUpdateOne is the builder for updating a single PaygOrder entity.
type PaygOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaygOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaygOrderUpdateOne) SetUpdatedAt(v time.Time) *PaygOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaygOrderUpdateOne) SetUserID(v int64) *PaygOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillableUserID(v *int64) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientSn sets the "client_sn" field.
func (_u *PaygOrderUpdateOne) SetClientSn(v string) *PaygOrderUpdateOne {
	_u.mutation.SetClientSn(v)
	return _u
}

// SetNillableClientSn sets the "client_sn" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillableClientSn(v *string) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetClientSn(*v)
	}
	return _u
}

// SetSn sets the "sn" field.
func (_u *PaygOrderUpdateOne) SetSn(v string) *PaygOrderUpdateOne {
	_u.mutation.SetSn(v)
	return _u
}

// SetNillableSn sets the "sn" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillableSn(v *string) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetSn(*v)
	}
	return _u
}

// ClearSn clears the value of the "sn" field.
func (_u *PaygOrderUpdateOne) ClearSn() *PaygOrderUpdateOne {
	_u.mutation.ClearSn()
	return _u
}

// SetAmountYuan sets the "amount_yuan" field.
func (_u *PaygOrderUpdateOne) SetAmountYuan(v float64) *PaygOrderUpdateOne {
	_u.mutation.ResetAmountYuan()
	_u.mutation.SetAmountYuan(v)
	return _u
}

// SetNillableAmountYuan sets the "amount_yuan" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillableAmountYuan(v *float64) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetAmountYuan(*v)
	}
	return _u
}

// AddAmountYuan adds value to the "amount_yuan" field.
func (_u *PaygOrderUpdateOne) AddAmountYuan(v float64) *PaygOrderUpdateOne {
	_u.mutation.AddAmountYuan(v)
	return _u
}

// SetAmountCent sets the "amount_cent" field.
func (_u *PaygOrderUpdateOne) SetAmountCent(v int64) *PaygOrderUpdateOne {
	_u.mutation.ResetAmountCent()
	_u.mutation.SetAmountCent(v)
	return _u
}

// SetNillableAmountCent sets the "amount_cent" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillableAmountCent(v *int64) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetAmountCent(*v)
	}
	return _u
}

// AddAmountCent adds value to the "amount_cent" field.
func (_u *PaygOrderUpdateOne) AddAmountCent(v int64) *PaygOrderUpdateOne {
	_u.mutation.AddAmountCent(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *PaygOrderUpdateOne) SetCreditAmount(v float64) *PaygOrderUpdateOne {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillableCreditAmount(v *float64) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *PaygOrderUpdateOne) AddCreditAmount(v float64) *PaygOrderUpdateOne {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetPayway sets the "payway" field.
func (_u *PaygOrderUpdateOne) SetPayway(v string) *PaygOrderUpdateOne {
	_u.mutation.SetPayway(v)
	return _u
}

// SetNillablePayway sets the "payway" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillablePayway(v *string) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetPayway(*v)
	}
	return _u
}

// SetPaywayName sets the "payway_name" field.
func (_u *PaygOrderUpdateOne) SetPaywayName(v string) *PaygOrderUpdateOne {
	_u.mutation.SetPaywayName(v)
	return _u
}

// SetNillablePaywayName sets the "payway_name" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillablePaywayName(v *string) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetPaywayName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaygOrderUpdateOne) SetStatus(v string) *PaygOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillableStatus(v *string) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaygOrderUpdateOne) SetPaidAt(v time.Time) *PaygOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaygOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaygOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaygOrderUpdateOne) ClearPaidAt() *PaygOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaygOrderUpdateOne) SetUser(v *User) *PaygOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaygOrderMutation object of the builder.
func (_u *PaygOrderUpdateOne) Mutation() *PaygOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaygOrderUpdateOne) ClearUser() *PaygOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaygOrderUpdate builder.
func (_u *PaygOrderUpdateOne) Where(ps ...predicate.PaygOrder) *PaygOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaygOrderUpdateOne) Select(field string, fields ...string) *PaygOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaygOrder entity.
func (_u *PaygOrderUpdateOne) Save(ctx context.Context) (*PaygOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaygOrderUpdateOne) SaveX(ctx context.Context) *PaygOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaygOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaygOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaygOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paygorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaygOrderUpdateOne) check() error {
	if v, ok := _u.mutation.ClientSn(); ok {
		if err := paygorder.ClientSnValidator(v); err != nil {
			return &ValidationError{Name: "client_sn", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.client_sn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sn(); ok {
		if err := paygorder.SnValidator(v); err != nil {
			return &ValidationError{Name: "sn", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.sn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Payway(); ok {
		if err := paygorder.PaywayValidator(v); err != nil {
			return &ValidationError{Name: "payway", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.payway": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaywayName(); ok {
		if err := paygorder.PaywayNameValidator(v); err != nil {
			return &ValidationError{Name: "payway_name", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.payway_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paygorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaygOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaygOrder.user"`)
	}
	return nil
}

func (_u *PaygOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaygOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paygorder.Table, paygorder.Columns, sqlgraph.NewFieldSpec(paygorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaygOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paygorder.FieldID)
		for _, f := range fields {
			if !paygorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paygorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paygorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientSn(); ok {
		_spec.SetField(paygorder.FieldClientSn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sn(); ok {
		_spec.SetField(paygorder.FieldSn, field.TypeString, value)
	}
	if _u.mutation.SnCleared() {
		_spec.ClearField(paygorder.FieldSn, field.TypeString)
	}
	if value, ok := _u.mutation.AmountYuan(); ok {
		_spec.SetField(paygorder.FieldAmountYuan, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountYuan(); ok {
		_spec.AddField(paygorder.FieldAmountYuan, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCent(); ok {
		_spec.SetField(paygorder.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCent(); ok {
		_spec.AddField(paygorder.FieldAmountCent, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(paygorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(paygorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Payway(); ok {
		_spec.SetField(paygorder.FieldPayway, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaywayName(); ok {
		_spec.SetField(paygorder.FieldPaywayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paygorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paygorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paygorder.FieldPaidAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paygorder.UserTable,
			Columns: []string{paygorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paygorder.UserTable,
			Columns: []string{paygorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaygOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paygorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
