// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referralreward"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralRewardCreate is the builder for creating a ReferralReward entity.
type ReferralRewardCreate struct {
	config
	mutation *ReferralRewardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetReferrerID sets the "referrer_id" field.
func (_c *ReferralRewardCreate) SetReferrerID(v int64) *ReferralRewardCreate {
	_c.mutation.SetReferrerID(v)
	return _c
}

// SetRefereeID sets the "referee_id" field.
func (_c *ReferralRewardCreate) SetRefereeID(v int64) *ReferralRewardCreate {
	_c.mutation.SetRefereeID(v)
	return _c
}

// SetRewardType sets the "reward_type" field.
func (_c *ReferralRewardCreate) SetRewardType(v string) *ReferralRewardCreate {
	_c.mutation.SetRewardType(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *ReferralRewardCreate) SetSourceType(v string) *ReferralRewardCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableSourceType(v *string) *ReferralRewardCreate {
	if v != nil {
		_c.SetSourceType(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ReferralRewardCreate) SetSourceID(v int64) *ReferralRewardCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableSourceID(v *int64) *ReferralRewardCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetSourceAmount sets the "source_amount" field.
func (_c *ReferralRewardCreate) SetSourceAmount(v float64) *ReferralRewardCreate {
	_c.mutation.SetSourceAmount(v)
	return _c
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableSourceAmount(v *float64) *ReferralRewardCreate {
	if v != nil {
		_c.SetSourceAmount(*v)
	}
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *ReferralRewardCreate) SetRewardAmount(v float64) *ReferralRewardCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetCommissionRate sets the "commission_rate" field.
func (_c *ReferralRewardCreate) SetCommissionRate(v float64) *ReferralRewardCreate {
	_c.mutation.SetCommissionRate(v)
	return _c
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableCommissionRate(v *float64) *ReferralRewardCreate {
	if v != nil {
		_c.SetCommissionRate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralRewardCreate) SetCreatedAt(v time.Time) *ReferralRewardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralRewardCreate) SetNillableCreatedAt(v *time.Time) *ReferralRewardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetReferrer sets the "referrer" edge to the User entity.
func (_c *ReferralRewardCreate) SetReferrer(v *User) *ReferralRewardCreate {
	return _c.SetReferrerID(v.ID)
}

// SetReferee sets the "referee" edge to the User entity.
func (_c *ReferralRewardCreate) SetReferee(v *User) *ReferralRewardCreate {
	return _c.SetRefereeID(v.ID)
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_c *ReferralRewardCreate) Mutation() *ReferralRewardMutation {
	return _c.mutation
}

// Save creates the ReferralReward in the database.
func (_c *ReferralRewardCreate) Save(ctx context.Context) (*ReferralReward, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralRewardCreate) SaveX(ctx context.Context) *ReferralReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralRewardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralRewardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralRewardCreate) defaults() {
	if _, ok := _c.mutation.SourceAmount(); !ok {
		v := referralreward.DefaultSourceAmount
		_c.mutation.SetSourceAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralreward.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralRewardCreate) check() error {
	if _, ok := _c.mutation.ReferrerID(); !ok {
		return &ValidationError{Name: "referrer_id", err: errors.New(`ent: missing required field "ReferralReward.referrer_id"`)}
	}
	if _, ok := _c.mutation.RefereeID(); !ok {
		return &ValidationError{Name: "referee_id", err: errors.New(`ent: missing required field "ReferralReward.referee_id"`)}
	}
	if _, ok := _c.mutation.RewardType(); !ok {
		return &ValidationError{Name: "reward_type", err: errors.New(`ent: missing required field "ReferralReward.reward_type"`)}
	}
	if v, ok := _c.mutation.RewardType(); ok {
		if err := referralreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.reward_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := referralreward.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceAmount(); !ok {
		return &ValidationError{Name: "source_amount", err: errors.New(`ent: missing required field "ReferralReward.source_amount"`)}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "ReferralReward.reward_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralReward.created_at"`)}
	}
	if len(_c.mutation.ReferrerIDs()) == 0 {
		return &ValidationError{Name: "referrer", err: errors.New(`ent: missing required edge "ReferralReward.referrer"`)}
	}
	if len(_c.mutation.RefereeIDs()) == 0 {
		return &ValidationError{Name: "referee", err: errors.New(`ent: missing required edge "ReferralReward.referee"`)}
	}
	return nil
}

func (_c *ReferralRewardCreate) sqlSave(ctx context.Context) (*ReferralReward, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralRewardCreate) createSpec() (*ReferralReward, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralReward{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralreward.Table, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RewardType(); ok {
		_spec.SetField(referralreward.FieldRewardType, field.TypeString, value)
		_node.RewardType = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(referralreward.FieldSourceType, field.TypeString, value)
		_node.SourceType = &value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(referralreward.FieldSourceID, field.TypeInt64, value)
		_node.SourceID = &value
	}
	if value, ok := _c.mutation.SourceAmount(); ok {
		_spec.SetField(referralreward.FieldSourceAmount, field.TypeFloat64, value)
		_node.SourceAmount = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.CommissionRate(); ok {
		_spec.SetField(referralreward.FieldCommissionRate, field.TypeFloat64, value)
		_node.CommissionRate = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralreward.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ReferrerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.ReferrerTable,
			Columns: []string{referralreward.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReferrerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RefereeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.RefereeTable,
			Columns: []string{referralreward.RefereeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RefereeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralReward.Create().
//		SetReferrerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralRewardUpsert) {
//			SetReferrerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralRewardCreate) OnConflict(opts ...sql.ConflictOption) *ReferralRewardUpsertOne {
	_c.conflict = opts
	return &ReferralRewardUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralRewardCreate) OnConflictColumns(columns ...string) *ReferralRewardUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralRewardUpsertOne{
		create: _c,
	}
}

type (
	// ReferralRewardUpsertOne is the builder for "upsert"-ing
	//  one ReferralReward node.
	ReferralRewardUpsertOne struct {
		create *ReferralRewardCreate
	}

	// ReferralRewardUpsert is the "OnConflict" setter.
	ReferralRewardUpsert struct {
		*sql.UpdateSet
	}
)

// SetReferrerID sets the "referrer_id" field.
func (u *ReferralRewardUpsert) SetReferrerID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldReferrerID, v)
	return u
}

// UpdateReferrerID sets the "referrer_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateReferrerID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldReferrerID)
	return u
}

// SetRefereeID sets the "referee_id" field.
func (u *ReferralRewardUpsert) SetRefereeID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRefereeID, v)
	return u
}

// UpdateRefereeID sets the "referee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRefereeID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRefereeID)
	return u
}

// SetRewardType sets the "reward_type" field.
func (u *ReferralRewardUpsert) SetRewardType(v string) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRewardType, v)
	return u
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRewardType() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRewardType)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *ReferralRewardUpsert) SetSourceType(v string) *ReferralRewardUpsert {
	u.Set(referralreward.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateSourceType() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldSourceType)
	return u
}

// ClearSourceType clears the value of the "source_type" field.
func (u *ReferralRewardUpsert) ClearSourceType() *ReferralRewardUpsert {
	u.SetNull(referralreward.FieldSourceType)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *ReferralRewardUpsert) SetSourceID(v int64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateSourceID() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldSourceID)
	return u
}

// AddSourceID adds v to the "source_id" field.
func (u *ReferralRewardUpsert) AddSourceID(v int64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldSourceID, v)
	return u
}

// ClearSourceID clears the value of the "source_id" field.
func (u *ReferralRewardUpsert) ClearSourceID() *ReferralRewardUpsert {
	u.SetNull(referralreward.FieldSourceID)
	return u
}

// SetSourceAmount sets the "source_amount" field.
func (u *ReferralRewardUpsert) SetSourceAmount(v float64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldSourceAmount, v)
	return u
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateSourceAmount() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldSourceAmount)
	return u
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *ReferralRewardUpsert) AddSourceAmount(v float64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldSourceAmount, v)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsert) SetRewardAmount(v float64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateRewardAmount() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsert) AddRewardAmount(v float64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldRewardAmount, v)
	return u
}

// SetCommissionRate sets the "commission_rate" field.
func (u *ReferralRewardUpsert) SetCommissionRate(v float64) *ReferralRewardUpsert {
	u.Set(referralreward.FieldCommissionRate, v)
	return u
}

// UpdateCommissionRate sets the "commission_rate" field to the value that was provided on create.
func (u *ReferralRewardUpsert) UpdateCommissionRate() *ReferralRewardUpsert {
	u.SetExcluded(referralreward.FieldCommissionRate)
	return u
}

// AddCommissionRate adds v to the "commission_rate" field.
func (u *ReferralRewardUpsert) AddCommissionRate(v float64) *ReferralRewardUpsert {
	u.Add(referralreward.FieldCommissionRate, v)
	return u
}

// ClearCommissionRate clears the value of the "commission_rate" field.
func (u *ReferralRewardUpsert) ClearCommissionRate() *ReferralRewardUpsert {
	u.SetNull(referralreward.FieldCommissionRate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralRewardUpsertOne) UpdateNewValues() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralreward.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralRewardUpsertOne) Ignore() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralRewardUpsertOne) DoNothing() *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralRewardCreate.OnConflict
// documentation for more info.
func (u *ReferralRewardUpsertOne) Update(set func(*ReferralRewardUpsert)) *ReferralRewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetReferrerID sets the "referrer_id" field.
func (u *ReferralRewardUpsertOne) SetReferrerID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetReferrerID(v)
	})
}

// UpdateReferrerID sets the "referrer_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateReferrerID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateReferrerID()
	})
}

// SetRefereeID sets the "referee_id" field.
func (u *ReferralRewardUpsertOne) SetRefereeID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRefereeID(v)
	})
}

// UpdateRefereeID sets the "referee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRefereeID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRefereeID()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *ReferralRewardUpsertOne) SetRewardType(v string) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRewardType() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardType()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ReferralRewardUpsertOne) SetSourceType(v string) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateSourceType() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceType()
	})
}

// ClearSourceType clears the value of the "source_type" field.
func (u *ReferralRewardUpsertOne) ClearSourceType() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ReferralRewardUpsertOne) SetSourceID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *ReferralRewardUpsertOne) AddSourceID(v int64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateSourceID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *ReferralRewardUpsertOne) ClearSourceID() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearSourceID()
	})
}

// SetSourceAmount sets the "source_amount" field.
func (u *ReferralRewardUpsertOne) SetSourceAmount(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceAmount(v)
	})
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *ReferralRewardUpsertOne) AddSourceAmount(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddSourceAmount(v)
	})
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateSourceAmount() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceAmount()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsertOne) SetRewardAmount(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsertOne) AddRewardAmount(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateRewardAmount() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetCommissionRate sets the "commission_rate" field.
func (u *ReferralRewardUpsertOne) SetCommissionRate(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetCommissionRate(v)
	})
}

// AddCommissionRate adds v to the "commission_rate" field.
func (u *ReferralRewardUpsertOne) AddCommissionRate(v float64) *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddCommissionRate(v)
	})
}

// UpdateCommissionRate sets the "commission_rate" field to the value that was provided on create.
func (u *ReferralRewardUpsertOne) UpdateCommissionRate() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateCommissionRate()
	})
}

// ClearCommissionRate clears the value of the "commission_rate" field.
func (u *ReferralRewardUpsertOne) ClearCommissionRate() *ReferralRewardUpsertOne {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearCommissionRate()
	})
}

// Exec executes the query.
func (u *ReferralRewardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralRewardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralRewardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralRewardUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralRewardUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralRewardCreateBulk is the builder for creating many ReferralReward entities in bulk.
type ReferralRewardCreateBulk struct {
	config
	err      error
	builders []*ReferralRewardCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralReward entities in the database.
func (_c *ReferralRewardCreateBulk) Save(ctx context.Context) ([]*ReferralReward, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralReward, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralRewardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralRewardCreateBulk) SaveX(ctx context.Context) []*ReferralReward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralRewardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralRewardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralReward.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralRewardUpsert) {
//			SetReferrerID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralRewardCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralRewardUpsertBulk {
	_c.conflict = opts
	return &ReferralRewardUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralRewardCreateBulk) OnConflictColumns(columns ...string) *ReferralRewardUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralRewardUpsertBulk{
		create: _c,
	}
}

// ReferralRewardUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralReward nodes.
type ReferralRewardUpsertBulk struct {
	create *ReferralRewardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralRewardUpsertBulk) UpdateNewValues() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralreward.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralReward.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralRewardUpsertBulk) Ignore() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralRewardUpsertBulk) DoNothing() *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralRewardCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralRewardUpsertBulk) Update(set func(*ReferralRewardUpsert)) *ReferralRewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralRewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetReferrerID sets the "referrer_id" field.
func (u *ReferralRewardUpsertBulk) SetReferrerID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetReferrerID(v)
	})
}

// UpdateReferrerID sets the "referrer_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateReferrerID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateReferrerID()
	})
}

// SetRefereeID sets the "referee_id" field.
func (u *ReferralRewardUpsertBulk) SetRefereeID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRefereeID(v)
	})
}

// UpdateRefereeID sets the "referee_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRefereeID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRefereeID()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *ReferralRewardUpsertBulk) SetRewardType(v string) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRewardType() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardType()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ReferralRewardUpsertBulk) SetSourceType(v string) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateSourceType() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceType()
	})
}

// ClearSourceType clears the value of the "source_type" field.
func (u *ReferralRewardUpsertBulk) ClearSourceType() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearSourceType()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ReferralRewardUpsertBulk) SetSourceID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceID(v)
	})
}

// AddSourceID adds v to the "source_id" field.
func (u *ReferralRewardUpsertBulk) AddSourceID(v int64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateSourceID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceID()
	})
}

// ClearSourceID clears the value of the "source_id" field.
func (u *ReferralRewardUpsertBulk) ClearSourceID() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearSourceID()
	})
}

// SetSourceAmount sets the "source_amount" field.
func (u *ReferralRewardUpsertBulk) SetSourceAmount(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetSourceAmount(v)
	})
}

// AddSourceAmount adds v to the "source_amount" field.
func (u *ReferralRewardUpsertBulk) AddSourceAmount(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddSourceAmount(v)
	})
}

// UpdateSourceAmount sets the "source_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateSourceAmount() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateSourceAmount()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ReferralRewardUpsertBulk) SetRewardAmount(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ReferralRewardUpsertBulk) AddRewardAmount(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateRewardAmount() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetCommissionRate sets the "commission_rate" field.
func (u *ReferralRewardUpsertBulk) SetCommissionRate(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.SetCommissionRate(v)
	})
}

// AddCommissionRate adds v to the "commission_rate" field.
func (u *ReferralRewardUpsertBulk) AddCommissionRate(v float64) *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.AddCommissionRate(v)
	})
}

// UpdateCommissionRate sets the "commission_rate" field to the value that was provided on create.
func (u *ReferralRewardUpsertBulk) UpdateCommissionRate() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.UpdateCommissionRate()
	})
}

// ClearCommissionRate clears the value of the "commission_rate" field.
func (u *ReferralRewardUpsertBulk) ClearCommissionRate() *ReferralRewardUpsertBulk {
	return u.Update(func(s *ReferralRewardUpsert) {
		s.ClearCommissionRate()
	})
}

// Exec executes the query.
func (u *ReferralRewardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralRewardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralRewardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralRewardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
