// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralreward"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralReward is the model entity for the ReferralReward schema.
type ReferralReward struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 邀请人ID
	ReferrerID int64 `json:"referrer_id,omitempty"`
	// 被邀请人ID
	RefereeID int64 `json:"referee_id,omitempty"`
	// 奖励类型：register=注册奖励，commission=返利
	RewardType string `json:"reward_type,omitempty"`
	// 来源类型：redeem_code=兑换码
	SourceType *string `json:"source_type,omitempty"`
	// 来源ID
	SourceID *int64 `json:"source_id,omitempty"`
	// 来源金额
	SourceAmount float64 `json:"source_amount,omitempty"`
	// 奖励金额
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// 返利比例（仅 commission 类型）
	CommissionRate *float64 `json:"commission_rate,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReferralRewardQuery when eager-loading is set.
	Edges        ReferralRewardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReferralRewardEdges holds the relations/edges for other nodes in the graph.
type ReferralRewardEdges struct {
	// Referrer holds the value of the referrer edge.
	Referrer *User `json:"referrer,omitempty"`
	// Referee holds the value of the referee edge.
	Referee *User `json:"referee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ReferrerOrErr returns the Referrer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralRewardEdges) ReferrerOrErr() (*User, error) {
	if e.Referrer != nil {
		return e.Referrer, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "referrer"}
}

// RefereeOrErr returns the Referee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralRewardEdges) RefereeOrErr() (*User, error) {
	if e.Referee != nil {
		return e.Referee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "referee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralReward) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralreward.FieldSourceAmount, referralreward.FieldRewardAmount, referralreward.FieldCommissionRate:
			values[i] = new(sql.NullFloat64)
		case referralreward.FieldID, referralreward.FieldReferrerID, referralreward.FieldRefereeID, referralreward.FieldSourceID:
			values[i] = new(sql.NullInt64)
		case referralreward.FieldRewardType, referralreward.FieldSourceType:
			values[i] = new(sql.NullString)
		case referralreward.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralReward fields.
func (_m *ReferralReward) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralreward.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralreward.FieldReferrerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_id", values[i])
			} else if value.Valid {
				_m.ReferrerID = value.Int64
			}
		case referralreward.FieldRefereeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referee_id", values[i])
			} else if value.Valid {
				_m.RefereeID = value.Int64
			}
		case referralreward.FieldRewardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_type", values[i])
			} else if value.Valid {
				_m.RewardType = value.String
			}
		case referralreward.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = new(string)
				*_m.SourceType = value.String
			}
		case referralreward.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = new(int64)
				*_m.SourceID = value.Int64
			}
		case referralreward.FieldSourceAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field source_amount", values[i])
			} else if value.Valid {
				_m.SourceAmount = value.Float64
			}
		case referralreward.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case referralreward.FieldCommissionRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_rate", values[i])
			} else if value.Valid {
				_m.CommissionRate = new(float64)
				*_m.CommissionRate = value.Float64
			}
		case referralreward.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralReward.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralReward) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReferrer queries the "referrer" edge of the ReferralReward entity.
func (_m *ReferralReward) QueryReferrer() *UserQuery {
	return NewReferralRewardClient(_m.config).QueryReferrer(_m)
}

// QueryReferee queries the "referee" edge of the ReferralReward entity.
func (_m *ReferralReward) QueryReferee() *UserQuery {
	return NewReferralRewardClient(_m.config).QueryReferee(_m)
}

// Update returns a builder for updating this ReferralReward.
// Note that you need to call ReferralReward.Unwrap() before calling this method if this ReferralReward
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralReward) Update() *ReferralRewardUpdateOne {
	return NewReferralRewardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralReward entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralReward) Unwrap() *ReferralReward {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralReward is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralReward) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralReward(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("referrer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferrerID))
	builder.WriteString(", ")
	builder.WriteString("referee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefereeID))
	builder.WriteString(", ")
	builder.WriteString("reward_type=")
	builder.WriteString(_m.RewardType)
	builder.WriteString(", ")
	if v := _m.SourceType; v != nil {
		builder.WriteString("source_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SourceID; v != nil {
		builder.WriteString("source_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceAmount))
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	if v := _m.CommissionRate; v != nil {
		builder.WriteString("commission_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralRewards is a parsable slice of ReferralReward.
type ReferralRewards []*ReferralReward
