// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralreward"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralRewardUpdate is the builder for updating ReferralReward entities.
type ReferralRewardUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralRewardMutation
}

// Where appends a list predicates to the ReferralRewardUpdate builder.
func (_u *ReferralRewardUpdate) Where(ps ...predicate.ReferralReward) *ReferralRewardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReferrerID sets the "referrer_id" field.
func (_u *ReferralRewardUpdate) SetReferrerID(v int64) *ReferralRewardUpdate {
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableReferrerID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// SetRefereeID sets the "referee_id" field.
func (_u *ReferralRewardUpdate) SetRefereeID(v int64) *ReferralRewardUpdate {
	_u.mutation.SetRefereeID(v)
	return _u
}

// SetNillableRefereeID sets the "referee_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRefereeID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRefereeID(*v)
	}
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *ReferralRewardUpdate) SetRewardType(v string) *ReferralRewardUpdate {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRewardType(v *string) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ReferralRewardUpdate) SetSourceType(v string) *ReferralRewardUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableSourceType(v *string) *ReferralRewardUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// ClearSourceType clears the value of the "source_type" field.
func (_u *ReferralRewardUpdate) ClearSourceType() *ReferralRewardUpdate {
	_u.mutation.ClearSourceType()
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ReferralRewardUpdate) SetSourceID(v int64) *ReferralRewardUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableSourceID(v *int64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *ReferralRewardUpdate) AddSourceID(v int64) *ReferralRewardUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ReferralRewardUpdate) ClearSourceID() *ReferralRewardUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceAmount sets the "source_amount" field.
func (_u *ReferralRewardUpdate) SetSourceAmount(v float64) *ReferralRewardUpdate {
	_u.mutation.ResetSourceAmount()
	_u.mutation.SetSourceAmount(v)
	return _u
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableSourceAmount(v *float64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetSourceAmount(*v)
	}
	return _u
}

// AddSourceAmount adds value to the "source_amount" field.
func (_u *ReferralRewardUpdate) AddSourceAmount(v float64) *ReferralRewardUpdate {
	_u.mutation.AddSourceAmount(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ReferralRewardUpdate) SetRewardAmount(v float64) *ReferralRewardUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableRewardAmount(v *float64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ReferralRewardUpdate) AddRewardAmount(v float64) *ReferralRewardUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *ReferralRewardUpdate) SetCommissionRate(v float64) *ReferralRewardUpdate {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *ReferralRewardUpdate) SetNillableCommissionRate(v *float64) *ReferralRewardUpdate {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *ReferralRewardUpdate) AddCommissionRate(v float64) *ReferralRewardUpdate {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// ClearCommissionRate clears the value of the "commission_rate" field.
func (_u *ReferralRewardUpdate) ClearCommissionRate() *ReferralRewardUpdate {
	_u.mutation.ClearCommissionRate()
	return _u
}

// SetReferrer sets the "referrer" edge to the User entity.
func (_u *ReferralRewardUpdate) SetReferrer(v *User) *ReferralRewardUpdate {
	return _u.SetReferrerID(v.ID)
}

// SetReferee sets the "referee" edge to the User entity.
func (_u *ReferralRewardUpdate) SetReferee(v *User) *ReferralRewardUpdate {
	return _u.SetRefereeID(v.ID)
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_u *ReferralRewardUpdate) Mutation() *ReferralRewardMutation {
	return _u.mutation
}

// ClearReferrer clears the "referrer" edge to the User entity.
func (_u *ReferralRewardUpdate) ClearReferrer() *ReferralRewardUpdate {
	_u.mutation.ClearReferrer()
	return _u
}

// ClearReferee clears the "referee" edge to the User entity.
func (_u *ReferralRewardUpdate) ClearReferee() *ReferralRewardUpdate {
	_u.mutation.ClearReferee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralRewardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralRewardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralRewardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralRewardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralRewardUpdate) check() error {
	if v, ok := _u.mutation.RewardType(); ok {
		if err := referralreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.reward_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := referralreward.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.source_type": %w`, err)}
		}
	}
	if _u.mutation.ReferrerCleared() && len(_u.mutation.ReferrerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralReward.referrer"`)
	}
	if _u.mutation.RefereeCleared() && len(_u.mutation.RefereeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralReward.referee"`)
	}
	return nil
}

func (_u *ReferralRewardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralreward.Table, referralreward.Columns, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(referralreward.FieldRewardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(referralreward.FieldSourceType, field.TypeString, value)
	}
	if _u.mutation.SourceTypeCleared() {
		_spec.ClearField(referralreward.FieldSourceType, field.TypeString)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(referralreward.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(referralreward.FieldSourceID, field.TypeInt64, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(referralreward.FieldSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceAmount(); ok {
		_spec.SetField(referralreward.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceAmount(); ok {
		_spec.AddField(referralreward.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(referralreward.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(referralreward.FieldCommissionRate, field.TypeFloat64, value)
	}
	if _u.mutation.CommissionRateCleared() {
		_spec.ClearField(referralreward.FieldCommissionRate, field.TypeFloat64)
	}
	if _u.mutation.ReferrerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.ReferrerTable,
			Columns: []string{referralreward.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferrerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.ReferrerTable,
			Columns: []string{referralreward.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RefereeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.RefereeTable,
			Columns: []string{referralreward.RefereeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefereeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.RefereeTable,
			Columns: []string{referralreward.RefereeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralRewardUpdateOne is the builder for updating a single ReferralReward entity.
type ReferralRewardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralRewardMutation
}

// SetReferrerID sets the "referrer_id" field.
func (_u *ReferralRewardUpdateOne) SetReferrerID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableReferrerID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// SetRefereeID sets the "referee_id" field.
func (_u *ReferralRewardUpdateOne) SetRefereeID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.SetRefereeID(v)
	return _u
}

// SetNillableRefereeID sets the "referee_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRefereeID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRefereeID(*v)
	}
	return _u
}

// SetRewardType sets the "reward_type" field.
func (_u *ReferralRewardUpdateOne) SetRewardType(v string) *ReferralRewardUpdateOne {
	_u.mutation.SetRewardType(v)
	return _u
}

// SetNillableRewardType sets the "reward_type" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRewardType(v *string) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRewardType(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ReferralRewardUpdateOne) SetSourceType(v string) *ReferralRewardUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableSourceType(v *string) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// ClearSourceType clears the value of the "source_type" field.
func (_u *ReferralRewardUpdateOne) ClearSourceType() *ReferralRewardUpdateOne {
	_u.mutation.ClearSourceType()
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ReferralRewardUpdateOne) SetSourceID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableSourceID(v *int64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *ReferralRewardUpdateOne) AddSourceID(v int64) *ReferralRewardUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ReferralRewardUpdateOne) ClearSourceID() *ReferralRewardUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceAmount sets the "source_amount" field.
func (_u *ReferralRewardUpdateOne) SetSourceAmount(v float64) *ReferralRewardUpdateOne {
	_u.mutation.ResetSourceAmount()
	_u.mutation.SetSourceAmount(v)
	return _u
}

// SetNillableSourceAmount sets the "source_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableSourceAmount(v *float64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetSourceAmount(*v)
	}
	return _u
}

// AddSourceAmount adds value to the "source_amount" field.
func (_u *ReferralRewardUpdateOne) AddSourceAmount(v float64) *ReferralRewardUpdateOne {
	_u.mutation.AddSourceAmount(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ReferralRewardUpdateOne) SetRewardAmount(v float64) *ReferralRewardUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableRewardAmount(v *float64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ReferralRewardUpdateOne) AddRewardAmount(v float64) *ReferralRewardUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *ReferralRewardUpdateOne) SetCommissionRate(v float64) *ReferralRewardUpdateOne {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *ReferralRewardUpdateOne) SetNillableCommissionRate(v *float64) *ReferralRewardUpdateOne {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *ReferralRewardUpdateOne) AddCommissionRate(v float64) *ReferralRewardUpdateOne {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// ClearCommissionRate clears the value of the "commission_rate" field.
func (_u *ReferralRewardUpdateOne) ClearCommissionRate() *ReferralRewardUpdateOne {
	_u.mutation.ClearCommissionRate()
	return _u
}

// SetReferrer sets the "referrer" edge to the User entity.
func (_u *ReferralRewardUpdateOne) SetReferrer(v *User) *ReferralRewardUpdateOne {
	return _u.SetReferrerID(v.ID)
}

// SetReferee sets the "referee" edge to the User entity.
func (_u *ReferralRewardUpdateOne) SetReferee(v *User) *ReferralRewardUpdateOne {
	return _u.SetRefereeID(v.ID)
}

// Mutation returns the ReferralRewardMutation object of the builder.
func (_u *ReferralRewardUpdateOne) Mutation() *ReferralRewardMutation {
	return _u.mutation
}

// ClearReferrer clears the "referrer" edge to the User entity.
func (_u *ReferralRewardUpdateOne) ClearReferrer() *ReferralRewardUpdateOne {
	_u.mutation.ClearReferrer()
	return _u
}

// ClearReferee clears the "referee" edge to the User entity.
func (_u *ReferralRewardUpdateOne) ClearReferee() *ReferralRewardUpdateOne {
	_u.mutation.ClearReferee()
	return _u
}

// Where appends a list predicates to the ReferralRewardUpdate builder.
func (_u *ReferralRewardUpdateOne) Where(ps ...predicate.ReferralReward) *ReferralRewardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralRewardUpdateOne) Select(field string, fields ...string) *ReferralRewardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralReward entity.
func (_u *ReferralRewardUpdateOne) Save(ctx context.Context) (*ReferralReward, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralRewardUpdateOne) SaveX(ctx context.Context) *ReferralReward {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralRewardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralRewardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralRewardUpdateOne) check() error {
	if v, ok := _u.mutation.RewardType(); ok {
		if err := referralreward.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.reward_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := referralreward.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ReferralReward.source_type": %w`, err)}
		}
	}
	if _u.mutation.ReferrerCleared() && len(_u.mutation.ReferrerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralReward.referrer"`)
	}
	if _u.mutation.RefereeCleared() && len(_u.mutation.RefereeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralReward.referee"`)
	}
	return nil
}

func (_u *ReferralRewardUpdateOne) sqlSave(ctx context.Context) (_node *ReferralReward, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralreward.Table, referralreward.Columns, sqlgraph.NewFieldSpec(referralreward.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralReward.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralreward.FieldID)
		for _, f := range fields {
			if !referralreward.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralreward.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RewardType(); ok {
		_spec.SetField(referralreward.FieldRewardType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(referralreward.FieldSourceType, field.TypeString, value)
	}
	if _u.mutation.SourceTypeCleared() {
		_spec.ClearField(referralreward.FieldSourceType, field.TypeString)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(referralreward.FieldSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(referralreward.FieldSourceID, field.TypeInt64, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(referralreward.FieldSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceAmount(); ok {
		_spec.SetField(referralreward.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceAmount(); ok {
		_spec.AddField(referralreward.FieldSourceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(referralreward.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(referralreward.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(referralreward.FieldCommissionRate, field.TypeFloat64, value)
	}
	if _u.mutation.CommissionRateCleared() {
		_spec.ClearField(referralreward.FieldCommissionRate, field.TypeFloat64)
	}
	if _u.mutation.ReferrerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.ReferrerTable,
			Columns: []string{referralreward.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferrerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.ReferrerTable,
			Columns: []string{referralreward.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RefereeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.RefereeTable,
			Columns: []string{referralreward.RefereeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefereeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralreward.RefereeTable,
			Columns: []string{referralreward.RefereeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReferralReward{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralreward.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
