// Code generated by ent, DO NOT EDIT.

package referralreward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the referralreward type in the database.
	Label = "referral_reward"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReferrerID holds the string denoting the referrer_id field in the database.
	FieldReferrerID = "referrer_id"
	// FieldRefereeID holds the string denoting the referee_id field in the database.
	FieldRefereeID = "referee_id"
	// FieldRewardType holds the string denoting the reward_type field in the database.
	FieldRewardType = "reward_type"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldSourceAmount holds the string denoting the source_amount field in the database.
	FieldSourceAmount = "source_amount"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// FieldCommissionRate holds the string denoting the commission_rate field in the database.
	FieldCommissionRate = "commission_rate"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeReferrer holds the string denoting the referrer edge name in mutations.
	EdgeReferrer = "referrer"
	// EdgeReferee holds the string denoting the referee edge name in mutations.
	EdgeReferee = "referee"
	// Table holds the table name of the referralreward in the database.
	Table = "referral_rewards"
	// ReferrerTable is the table that holds the referrer relation/edge.
	ReferrerTable = "referral_rewards"
	// ReferrerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReferrerInverseTable = "users"
	// ReferrerColumn is the table column denoting the referrer relation/edge.
	ReferrerColumn = "referrer_id"
	// RefereeTable is the table that holds the referee relation/edge.
	RefereeTable = "referral_rewards"
	// RefereeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	RefereeInverseTable = "users"
	// RefereeColumn is the table column denoting the referee relation/edge.
	RefereeColumn = "referee_id"
)

// Columns holds all SQL columns for referralreward fields.
var Columns = []string{
	FieldID,
	FieldReferrerID,
	FieldRefereeID,
	FieldRewardType,
	FieldSourceType,
	FieldSourceID,
	FieldSourceAmount,
	FieldRewardAmount,
	FieldCommissionRate,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RewardTypeValidator is a validator for the "reward_type" field. It is called by the builders before save.
	RewardTypeValidator func(string) error
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// DefaultSourceAmount holds the default value on creation for the "source_amount" field.
	DefaultSourceAmount float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralReward queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByReferrerID orders the results by the referrer_id field.
func ByReferrerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrerID, opts...).ToFunc()
}

// ByRefereeID orders the results by the referee_id field.
func ByRefereeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefereeID, opts...).ToFunc()
}

// ByRewardType orders the results by the reward_type field.
func ByRewardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardType, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// BySourceAmount orders the results by the source_amount field.
func BySourceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceAmount, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByCommissionRate orders the results by the commission_rate field.
func ByCommissionRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionRate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByReferrerField orders the results by referrer field.
func ByReferrerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferrerStep(), sql.OrderByField(field, opts...))
	}
}

// ByRefereeField orders the results by referee field.
func ByRefereeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRefereeStep(), sql.OrderByField(field, opts...))
	}
}
func newReferrerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferrerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
	)
}
func newRefereeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RefereeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RefereeTable, RefereeColumn),
	)
}
