// Code generated by ent, DO NOT EDIT.

package referralreward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldID, id))
}

// ReferrerID applies equality check predicate on the "referrer_id" field. It's identical to ReferrerIDEQ.
func ReferrerID(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldReferrerID, v))
}

// RefereeID applies equality check predicate on the "referee_id" field. It's identical to RefereeIDEQ.
func RefereeID(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRefereeID, v))
}

// RewardType applies equality check predicate on the "reward_type" field. It's identical to RewardTypeEQ.
func RewardType(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardType, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldSourceID, v))
}

// SourceAmount applies equality check predicate on the "source_amount" field. It's identical to SourceAmountEQ.
func SourceAmount(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldSourceAmount, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardAmount, v))
}

// CommissionRate applies equality check predicate on the "commission_rate" field. It's identical to CommissionRateEQ.
func CommissionRate(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldCommissionRate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldCreatedAt, v))
}

// ReferrerIDEQ applies the EQ predicate on the "referrer_id" field.
func ReferrerIDEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldReferrerID, v))
}

// ReferrerIDNEQ applies the NEQ predicate on the "referrer_id" field.
func ReferrerIDNEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldReferrerID, v))
}

// ReferrerIDIn applies the In predicate on the "referrer_id" field.
func ReferrerIDIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldReferrerID, vs...))
}

// ReferrerIDNotIn applies the NotIn predicate on the "referrer_id" field.
func ReferrerIDNotIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldReferrerID, vs...))
}

// RefereeIDEQ applies the EQ predicate on the "referee_id" field.
func RefereeIDEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRefereeID, v))
}

// RefereeIDNEQ applies the NEQ predicate on the "referee_id" field.
func RefereeIDNEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldRefereeID, v))
}

// RefereeIDIn applies the In predicate on the "referee_id" field.
func RefereeIDIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldRefereeID, vs...))
}

// RefereeIDNotIn applies the NotIn predicate on the "referee_id" field.
func RefereeIDNotIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldRefereeID, vs...))
}

// RewardTypeEQ applies the EQ predicate on the "reward_type" field.
func RewardTypeEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardType, v))
}

// RewardTypeNEQ applies the NEQ predicate on the "reward_type" field.
func RewardTypeNEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldRewardType, v))
}

// RewardTypeIn applies the In predicate on the "reward_type" field.
func RewardTypeIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldRewardType, vs...))
}

// RewardTypeNotIn applies the NotIn predicate on the "reward_type" field.
func RewardTypeNotIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldRewardType, vs...))
}

// RewardTypeGT applies the GT predicate on the "reward_type" field.
func RewardTypeGT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldRewardType, v))
}

// RewardTypeGTE applies the GTE predicate on the "reward_type" field.
func RewardTypeGTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldRewardType, v))
}

// RewardTypeLT applies the LT predicate on the "reward_type" field.
func RewardTypeLT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldRewardType, v))
}

// RewardTypeLTE applies the LTE predicate on the "reward_type" field.
func RewardTypeLTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldRewardType, v))
}

// RewardTypeContains applies the Contains predicate on the "reward_type" field.
func RewardTypeContains(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContains(FieldRewardType, v))
}

// RewardTypeHasPrefix applies the HasPrefix predicate on the "reward_type" field.
func RewardTypeHasPrefix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasPrefix(FieldRewardType, v))
}

// RewardTypeHasSuffix applies the HasSuffix predicate on the "reward_type" field.
func RewardTypeHasSuffix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasSuffix(FieldRewardType, v))
}

// RewardTypeEqualFold applies the EqualFold predicate on the "reward_type" field.
func RewardTypeEqualFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEqualFold(FieldRewardType, v))
}

// RewardTypeContainsFold applies the ContainsFold predicate on the "reward_type" field.
func RewardTypeContainsFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContainsFold(FieldRewardType, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeIsNil applies the IsNil predicate on the "source_type" field.
func SourceTypeIsNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIsNull(FieldSourceType))
}

// SourceTypeNotNil applies the NotNil predicate on the "source_type" field.
func SourceTypeNotNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotNull(FieldSourceType))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotNull(FieldSourceID))
}

// SourceAmountEQ applies the EQ predicate on the "source_amount" field.
func SourceAmountEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldSourceAmount, v))
}

// SourceAmountNEQ applies the NEQ predicate on the "source_amount" field.
func SourceAmountNEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldSourceAmount, v))
}

// SourceAmountIn applies the In predicate on the "source_amount" field.
func SourceAmountIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldSourceAmount, vs...))
}

// SourceAmountNotIn applies the NotIn predicate on the "source_amount" field.
func SourceAmountNotIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldSourceAmount, vs...))
}

// SourceAmountGT applies the GT predicate on the "source_amount" field.
func SourceAmountGT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldSourceAmount, v))
}

// SourceAmountGTE applies the GTE predicate on the "source_amount" field.
func SourceAmountGTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldSourceAmount, v))
}

// SourceAmountLT applies the LT predicate on the "source_amount" field.
func SourceAmountLT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldSourceAmount, v))
}

// SourceAmountLTE applies the LTE predicate on the "source_amount" field.
func SourceAmountLTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldSourceAmount, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldRewardAmount, v))
}

// CommissionRateEQ applies the EQ predicate on the "commission_rate" field.
func CommissionRateEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionRateNEQ applies the NEQ predicate on the "commission_rate" field.
func CommissionRateNEQ(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldCommissionRate, v))
}

// CommissionRateIn applies the In predicate on the "commission_rate" field.
func CommissionRateIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldCommissionRate, vs...))
}

// CommissionRateNotIn applies the NotIn predicate on the "commission_rate" field.
func CommissionRateNotIn(vs ...float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldCommissionRate, vs...))
}

// CommissionRateGT applies the GT predicate on the "commission_rate" field.
func CommissionRateGT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldCommissionRate, v))
}

// CommissionRateGTE applies the GTE predicate on the "commission_rate" field.
func CommissionRateGTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldCommissionRate, v))
}

// CommissionRateLT applies the LT predicate on the "commission_rate" field.
func CommissionRateLT(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldCommissionRate, v))
}

// CommissionRateLTE applies the LTE predicate on the "commission_rate" field.
func CommissionRateLTE(v float64) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldCommissionRate, v))
}

// CommissionRateIsNil applies the IsNil predicate on the "commission_rate" field.
func CommissionRateIsNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIsNull(FieldCommissionRate))
}

// CommissionRateNotNil applies the NotNil predicate on the "commission_rate" field.
func CommissionRateNotNil() predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotNull(FieldCommissionRate))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralReward {
	return predicate.ReferralReward(sql.FieldLTE(FieldCreatedAt, v))
}

// HasReferrer applies the HasEdge predicate on the "referrer" edge.
func HasReferrer() predicate.ReferralReward {
	return predicate.ReferralReward(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferrerWith applies the HasEdge predicate on the "referrer" edge with a given conditions (other predicates).
func HasReferrerWith(preds ...predicate.User) predicate.ReferralReward {
	return predicate.ReferralReward(func(s *sql.Selector) {
		step := newReferrerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferee applies the HasEdge predicate on the "referee" edge.
func HasReferee() predicate.ReferralReward {
	return predicate.ReferralReward(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RefereeTable, RefereeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRefereeWith applies the HasEdge predicate on the "referee" edge with a given conditions (other predicates).
func HasRefereeWith(preds ...predicate.User) predicate.ReferralReward {
	return predicate.ReferralReward(func(s *sql.Selector) {
		step := newRefereeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralReward) predicate.ReferralReward {
	return predicate.ReferralReward(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralReward) predicate.ReferralReward {
	return predicate.ReferralReward(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralReward) predicate.ReferralReward {
	return predicate.ReferralReward(sql.NotPredicates(p))
}
